// E2E verification: ggml DiT module outputs vs PyTorch gold reference.
//
// Gold data generated by: uv run python gen_e2e_dit_gold.py
// Output dir: /tmp/cv_e2e_dit_gold/
//
// Levels:
//   [e2e][dit1] TimestepEmbedding: SinusPosEmb → MLP
//   [e2e][dit2] Attention (block 0): QKV → RoPE → SDPA → Out
//   [e2e][dit3] FeedForward (block 0): Linear → GELU → Linear
//   [e2e][dit4] AdaLayerNormZero (block 0): SiLU → Linear → split → LN*scale+shift
//   [e2e][dit5] DiTBlock (block 0): AdaLN → Attn → FF → residual

#include <catch2/catch_test_macros.hpp>

#include <ggml.h>
#include <gguf.h>
#include <ggml-backend.h>
#include <ggml-cpu.h>

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <string>
#include <vector>

// ---- Constants ----
static const int D      = 1024;
static const int D_FF   = 2048;
static const int HEADS  = 16;
static const int HD     = D / HEADS;  // 64
static const int SEQ    = 10;
static const int HALF_DIM = 128;

static const char* GOLD_DIR = "/tmp/cv_e2e_dit_gold";

// ---- Gold file loader (headerful format) ----
struct gold_tensor {
    std::vector<int64_t> shape;
    std::vector<float>   data;
    int64_t numel() const { return static_cast<int64_t>(data.size()); }
};

static bool load_gold(const char* name, gold_tensor& out) {
    std::string path = std::string(GOLD_DIR) + "/" + name + ".bin";
    std::ifstream f(path, std::ios::binary);
    if (!f) return false;
    uint32_t ndim;
    f.read(reinterpret_cast<char*>(&ndim), 4);
    out.shape.resize(ndim);
    for (uint32_t i = 0; i < ndim; i++) {
        int64_t d;
        f.read(reinterpret_cast<char*>(&d), 8);
        out.shape[i] = d;
    }
    int64_t n = 1;
    for (auto d : out.shape) n *= d;
    out.data.resize(n);
    f.read(reinterpret_cast<char*>(out.data.data()), n * sizeof(float));
    return f.good();
}

// ---- GGUF loader ----
struct gguf_file {
    gguf_context* gguf_ctx = nullptr;
    ggml_context* ggml_ctx = nullptr;
    explicit gguf_file(const char* path) {
        gguf_ctx = gguf_init_from_file(path,
            gguf_init_params{.no_alloc = false, .ctx = &ggml_ctx});
    }
    ~gguf_file() {
        if (gguf_ctx) gguf_free(gguf_ctx);
        if (ggml_ctx) ggml_free(ggml_ctx);
    }
    explicit operator bool() const { return gguf_ctx != nullptr; }
    ggml_tensor* tensor(const char* name) const {
        return ggml_get_tensor(ggml_ctx, name);
    }
};

// ---- Helpers ----
static ggml_tensor* make_f32(ggml_context* ctx, int64_t n0, int64_t n1=1, int64_t n2=1, int64_t n3=1) {
    auto* t = ggml_new_tensor_4d(ctx, GGML_TYPE_F32, n0, n1, n2, n3);
    ggml_set_input(t);
    return t;
}

static void fill_from_gguf(ggml_tensor* dst, ggml_tensor* src) {
    int64_t n = ggml_nelements(src);
    if (src->type == GGML_TYPE_F32) {
        ggml_backend_tensor_set(dst, src->data, 0, n * sizeof(float));
    } else {
        std::vector<float> buf(n);
        ggml_get_type_traits(src->type)->to_float(src->data, buf.data(), n);
        ggml_backend_tensor_set(dst, buf.data(), 0, n * sizeof(float));
    }
}

struct cmp_result {
    float max_diff, mean_diff, mean_abs_diff;
    int first_idx; float first_got, first_exp;
};

static cmp_result compare(const float* got, const float* exp, int64_t n, float tol) {
    cmp_result r = {0, 0, 0, -1, 0, 0};
    double sd = 0, sa = 0;
    for (int64_t i = 0; i < n; i++) {
        float d = got[i] - exp[i];
        float a = std::abs(d);
        sd += d; sa += a;
        if (a > r.max_diff) r.max_diff = a;
        if (a > tol && r.first_idx < 0) {
            r.first_idx = (int)i; r.first_got = got[i]; r.first_exp = exp[i];
        }
    }
    r.mean_diff = (float)(sd / n);
    r.mean_abs_diff = (float)(sa / n);
    return r;
}

// Build ggml linear: y = x @ W^T + b  (W is [in, out] ggml ne)
static ggml_tensor* build_linear(ggml_context* ctx, ggml_tensor* x, ggml_tensor* w, ggml_tensor* b) {
    auto* y = ggml_mul_mat(ctx, w, x);
    if (b) {
        auto* bv = ggml_view_4d(ctx, b, b->ne[0], 1, 1, 1,
                                 b->nb[0], b->nb[0], b->nb[0], 0);
        y = ggml_add(ctx, y, bv);
    }
    return y;
}

// ---- Tests ----

SCENARIO("Given GGUF time_mlp weights and t=0.019, "
         "when TimestepEmbedding runs SinusPosEmb → MLP, "
         "then output matches PyTorch",
         "[e2e][dit1]") {

    auto* model_path = std::getenv("COSYVOICE_TEST_MODEL");
    if (!model_path) { SKIP("Set COSYVOICE_TEST_MODEL"); return; }

    gold_tensor gold_sinpos, gold_time_emb, gold_emb_coeff;
    if (!load_gold("level1_sinpos", gold_sinpos) ||
        !load_gold("level1_time_emb", gold_time_emb) ||
        !load_gold("level1_emb_coeff", gold_emb_coeff)) {
        SKIP("Gold files not found. Run: uv run python gen_e2e_dit_gold.py");
        return;
    }

    gguf_file model(model_path);
    REQUIRE(model);

    auto* mlp0_w_gguf = model.tensor("decoder.estimator.time_embed.time_mlp.0.weight");
    auto* mlp0_b_gguf = model.tensor("decoder.estimator.time_embed.time_mlp.0.bias");
    auto* mlp2_w_gguf = model.tensor("decoder.estimator.time_embed.time_mlp.2.weight");
    auto* mlp2_b_gguf = model.tensor("decoder.estimator.time_embed.time_mlp.2.bias");
    REQUIRE(mlp0_w_gguf); REQUIRE(mlp0_b_gguf);
    REQUIRE(mlp2_w_gguf); REQUIRE(mlp2_b_gguf);

    ggml_init_params params = { .mem_size = 64*1024*1024, .mem_buffer = nullptr, .no_alloc = true };
    auto* ctx = ggml_init(params);

    // SinusPosEmb: compute emb coefficients (same formula as cosyvoice-loader.cpp)
    auto* emb_coeff = make_f32(ctx, HALF_DIM);
    auto* t_in = make_f32(ctx, 1);

    // Build SinusPosEmb graph:
    // angles = t * emb_coeff  [HALF_DIM]
    // sinpos = cat(sin(angles), cos(angles))  [256]
    auto* t_rep = ggml_repeat(ctx, t_in, emb_coeff);  // [HALF_DIM]
    auto* angles = ggml_mul(ctx, t_rep, emb_coeff);     // [HALF_DIM]
    auto* sin_part = ggml_sin(ctx, angles);
    auto* cos_part = ggml_cos(ctx, angles);
    auto* sinpos = ggml_concat(ctx, sin_part, cos_part, 0);  // [256]
    ggml_set_output(sinpos);

    // MLP: Linear → SiLU → Linear
    auto* mlp0_w = make_f32(ctx, mlp0_w_gguf->ne[0], mlp0_w_gguf->ne[1]);
    auto* mlp0_b = make_f32(ctx, mlp0_b_gguf->ne[0]);
    auto* mlp2_w = make_f32(ctx, mlp2_w_gguf->ne[0], mlp2_w_gguf->ne[1]);
    auto* mlp2_b = make_f32(ctx, mlp2_b_gguf->ne[0]);

    auto* h = build_linear(ctx, sinpos, mlp0_w, mlp0_b);
    h = ggml_silu(ctx, h);
    auto* te_out = build_linear(ctx, h, mlp2_w, mlp2_b);
    ggml_set_output(te_out);

    auto* gf = ggml_new_graph_custom(ctx, 4096, false);
    ggml_build_forward_expand(gf, te_out);

    auto* backend = ggml_backend_cpu_init();
    auto* buf = ggml_backend_alloc_ctx_tensors(ctx, backend);
    REQUIRE(buf);

    // Fill data
    fill_from_gguf(mlp0_w, mlp0_w_gguf);
    fill_from_gguf(mlp0_b, mlp0_b_gguf);
    fill_from_gguf(mlp2_w, mlp2_w_gguf);
    fill_from_gguf(mlp2_b, mlp2_b_gguf);

    // Compute emb coefficients
    {
        std::vector<float> ec(HALF_DIM);
        for (int i = 0; i < HALF_DIM; i++)
            ec[i] = std::exp(i * (-std::log(10000.0f) / (HALF_DIM - 1))) * 1000.0f;
        ggml_backend_tensor_set(emb_coeff, ec.data(), 0, ec.size() * sizeof(float));
    }

    // Set t
    float t_val = 0.019f;
    ggml_backend_tensor_set(t_in, &t_val, 0, sizeof(float));

    auto status = ggml_backend_graph_compute(backend, gf);
    REQUIRE(status == GGML_STATUS_SUCCESS);

    THEN("SinusPosEmb output matches PyTorch") {
        std::vector<float> result(256);
        ggml_backend_tensor_get(sinpos, result.data(), 0, result.size() * sizeof(float));
        auto cmp = compare(result.data(), gold_sinpos.data.data(), 256, 1e-5f);
        INFO("sinpos: max_diff=" << cmp.max_diff << " mean_diff=" << cmp.mean_diff);
        REQUIRE(cmp.max_diff < 1e-4f);
    }

    THEN("TimestepEmbedding output matches PyTorch") {
        std::vector<float> result(D);
        ggml_backend_tensor_get(te_out, result.data(), 0, result.size() * sizeof(float));
        auto cmp = compare(result.data(), gold_time_emb.data.data(), D, 1e-3f);
        INFO("time_emb: max_diff=" << cmp.max_diff << " mean_diff=" << cmp.mean_diff);
        if (cmp.first_idx >= 0)
            INFO("first mismatch at " << cmp.first_idx
                 << ": got=" << cmp.first_got << " exp=" << cmp.first_exp);
        REQUIRE(cmp.max_diff < 5e-3f);
    }

    ggml_backend_buffer_free(buf);
    ggml_backend_free(backend);
    ggml_free(ctx);
}


SCENARIO("Given GGUF block 0 FF weights and deterministic input, "
         "when FeedForward runs Linear → GELU → Linear, "
         "then output matches PyTorch",
         "[e2e][dit3]") {

    auto* model_path = std::getenv("COSYVOICE_TEST_MODEL");
    if (!model_path) { SKIP("Set COSYVOICE_TEST_MODEL"); return; }

    gold_tensor gold_input, gold_output;
    if (!load_gold("level3_ff_input", gold_input) ||
        !load_gold("level3_ff_output", gold_output)) {
        SKIP("Gold files not found");
        return;
    }

    gguf_file model(model_path);
    REQUIRE(model);

    auto* up_w_gguf = model.tensor("decoder.estimator.transformer_blocks.0.ff.ff.0.0.weight");
    auto* up_b_gguf = model.tensor("decoder.estimator.transformer_blocks.0.ff.ff.0.0.bias");
    auto* dn_w_gguf = model.tensor("decoder.estimator.transformer_blocks.0.ff.ff.2.weight");
    auto* dn_b_gguf = model.tensor("decoder.estimator.transformer_blocks.0.ff.ff.2.bias");
    REQUIRE(up_w_gguf); REQUIRE(up_b_gguf);
    REQUIRE(dn_w_gguf); REQUIRE(dn_b_gguf);

    ggml_init_params params = { .mem_size = 128*1024*1024, .mem_buffer = nullptr, .no_alloc = true };
    auto* ctx = ggml_init(params);

    // Input: [D, SEQ, 1]
    auto* x = make_f32(ctx, D, SEQ, 1);
    auto* up_w = make_f32(ctx, up_w_gguf->ne[0], up_w_gguf->ne[1]);
    auto* up_b = make_f32(ctx, up_b_gguf->ne[0]);
    auto* dn_w = make_f32(ctx, dn_w_gguf->ne[0], dn_w_gguf->ne[1]);
    auto* dn_b = make_f32(ctx, dn_b_gguf->ne[0]);

    // FF: up → GELU → down
    auto* h = build_linear(ctx, x, up_w, up_b);
    h = ggml_gelu(ctx, h);
    auto* out = build_linear(ctx, h, dn_w, dn_b);
    ggml_set_output(out);

    auto* gf = ggml_new_graph_custom(ctx, 4096, false);
    ggml_build_forward_expand(gf, out);

    auto* backend = ggml_backend_cpu_init();
    auto* buf = ggml_backend_alloc_ctx_tensors(ctx, backend);
    REQUIRE(buf);

    fill_from_gguf(up_w, up_w_gguf);
    fill_from_gguf(up_b, up_b_gguf);
    fill_from_gguf(dn_w, dn_w_gguf);
    fill_from_gguf(dn_b, dn_b_gguf);
    ggml_backend_tensor_set(x, gold_input.data.data(), 0, gold_input.data.size() * sizeof(float));

    REQUIRE(ggml_backend_graph_compute(backend, gf) == GGML_STATUS_SUCCESS);

    THEN("FeedForward output matches PyTorch") {
        std::vector<float> result(SEQ * D);
        ggml_backend_tensor_get(out, result.data(), 0, result.size() * sizeof(float));
        auto cmp = compare(result.data(), gold_output.data.data(), SEQ * D, 5e-2f);
        INFO("ff: max_diff=" << cmp.max_diff << " mean_abs_diff=" << cmp.mean_abs_diff);
        if (cmp.first_idx >= 0)
            INFO("first mismatch at " << cmp.first_idx
                 << ": got=" << cmp.first_got << " exp=" << cmp.first_exp);
        REQUIRE(cmp.max_diff < 5e-1f);
    }

    ggml_backend_buffer_free(buf);
    ggml_backend_free(backend);
    ggml_free(ctx);
}


// ---- Helpers for AdaLN ----

static ggml_tensor* unsqueeze(ggml_context* ctx, ggml_tensor* x, int dim) {
    if (dim == 0)
        return ggml_view_4d(ctx, x, 1, x->ne[0], x->ne[1], x->ne[2], x->nb[0], x->nb[1], x->nb[2], 0);
    else if (dim == 1)
        return ggml_view_4d(ctx, x, x->ne[0], 1, x->ne[1], x->ne[2], x->nb[1], x->nb[1], x->nb[2], 0);
    else
        return ggml_view_4d(ctx, x, x->ne[0], x->ne[1], 1, x->ne[2], x->nb[1], x->nb[2], x->nb[2], 0);
}

static void split_tensor6(ggml_context* ctx, ggml_tensor* t, ggml_tensor** out) {
    int64_t chunk = t->ne[0] / 6;
    for (int i = 0; i < 6; i++)
        out[i] = ggml_view_1d(ctx, t, chunk, i * chunk * sizeof(float));
}


SCENARIO("Given GGUF block 0 AdaLayerNormZero weights, x and time embedding, "
         "when SiLU → Linear → split → LN*scale+shift runs, "
         "then norm output and gates match PyTorch",
         "[e2e][dit4]") {

    auto* model_path = std::getenv("COSYVOICE_TEST_MODEL");
    if (!model_path) { SKIP("Set COSYVOICE_TEST_MODEL"); return; }

    gold_tensor gold_x, gold_emb, gold_norm_out, gold_gate_msa, gold_shift_mlp, gold_scale_mlp, gold_gate_mlp;
    if (!load_gold("level4_adaln_x", gold_x) ||
        !load_gold("level4_adaln_emb", gold_emb) ||
        !load_gold("level4_adaln_norm_out", gold_norm_out) ||
        !load_gold("level4_adaln_gate_msa", gold_gate_msa) ||
        !load_gold("level4_adaln_shift_mlp", gold_shift_mlp) ||
        !load_gold("level4_adaln_scale_mlp", gold_scale_mlp) ||
        !load_gold("level4_adaln_gate_mlp", gold_gate_mlp)) {
        SKIP("Gold files not found");
        return;
    }

    gguf_file model(model_path);
    REQUIRE(model);

    auto* lin_w_gguf = model.tensor("decoder.estimator.transformer_blocks.0.attn_norm.linear.weight");
    auto* lin_b_gguf = model.tensor("decoder.estimator.transformer_blocks.0.attn_norm.linear.bias");
    REQUIRE(lin_w_gguf); REQUIRE(lin_b_gguf);

    ggml_init_params params = { .mem_size = 128*1024*1024, .mem_buffer = nullptr, .no_alloc = true };
    auto* ctx = ggml_init(params);

    auto* x = make_f32(ctx, D, SEQ, 1);
    auto* emb = make_f32(ctx, D);
    auto* lin_w = make_f32(ctx, lin_w_gguf->ne[0], lin_w_gguf->ne[1]);
    auto* lin_b = make_f32(ctx, lin_b_gguf->ne[0]);

    // SiLU(emb) → Linear → split×6
    auto* emb_silu = ggml_silu(ctx, emb);
    auto* emb_proj = build_linear(ctx, emb_silu, lin_w, lin_b);

    ggml_tensor* chunks[6];
    split_tensor6(ctx, emb_proj, chunks);
    auto* shift_msa = ggml_cont(ctx, chunks[0]);
    auto* scale_msa = ggml_cont(ctx, chunks[1]);
    auto* gate_msa  = ggml_cont(ctx, chunks[2]);
    auto* shift_mlp = ggml_cont(ctx, chunks[3]);
    auto* scale_mlp = ggml_cont(ctx, chunks[4]);
    auto* gate_mlp  = ggml_cont(ctx, chunks[5]);

    scale_msa = ggml_scale_bias(ctx, scale_msa, 1.f, 1.f);
    auto* scale_mlp_plus1 = ggml_scale_bias(ctx, scale_mlp, 1.f, 1.f);

    auto* x_norm = ggml_norm(ctx, x, 1e-6f);
    auto* norm_out = ggml_mul(ctx, x_norm, unsqueeze(ctx, scale_msa, 1));
    norm_out = ggml_add(ctx, norm_out, unsqueeze(ctx, shift_msa, 1));
    ggml_set_output(norm_out);
    ggml_set_output(gate_msa);
    ggml_set_output(shift_mlp);
    ggml_set_output(scale_mlp_plus1);
    ggml_set_output(gate_mlp);

    auto* gf = ggml_new_graph_custom(ctx, 4096, false);
    ggml_build_forward_expand(gf, norm_out);
    ggml_build_forward_expand(gf, gate_msa);
    ggml_build_forward_expand(gf, shift_mlp);
    ggml_build_forward_expand(gf, scale_mlp_plus1);
    ggml_build_forward_expand(gf, gate_mlp);

    auto* backend = ggml_backend_cpu_init();
    auto* buf = ggml_backend_alloc_ctx_tensors(ctx, backend);
    REQUIRE(buf);

    fill_from_gguf(lin_w, lin_w_gguf);
    fill_from_gguf(lin_b, lin_b_gguf);
    ggml_backend_tensor_set(x, gold_x.data.data(), 0, gold_x.data.size() * sizeof(float));
    ggml_backend_tensor_set(emb, gold_emb.data.data(), 0, gold_emb.data.size() * sizeof(float));

    REQUIRE(ggml_backend_graph_compute(backend, gf) == GGML_STATUS_SUCCESS);

    THEN("norm output matches PyTorch") {
        std::vector<float> result(SEQ * D);
        ggml_backend_tensor_get(norm_out, result.data(), 0, result.size() * sizeof(float));
        auto cmp = compare(result.data(), gold_norm_out.data.data(), SEQ * D, 1e-2f);
        INFO("adaln norm_out: max_diff=" << cmp.max_diff << " mean_abs_diff=" << cmp.mean_abs_diff);
        if (cmp.first_idx >= 0)
            INFO("first mismatch at " << cmp.first_idx
                 << ": got=" << cmp.first_got << " exp=" << cmp.first_exp);
        REQUIRE(cmp.max_diff < 5e-2f);
    }

    THEN("gate_msa matches PyTorch") {
        std::vector<float> result(D);
        ggml_backend_tensor_get(gate_msa, result.data(), 0, D * sizeof(float));
        auto cmp = compare(result.data(), gold_gate_msa.data.data(), D, 5e-3f);
        INFO("gate_msa: max_diff=" << cmp.max_diff);
        REQUIRE(cmp.max_diff < 1e-2f);
    }

    THEN("scale_mlp (+1) matches PyTorch") {
        std::vector<float> result(D);
        ggml_backend_tensor_get(scale_mlp_plus1, result.data(), 0, D * sizeof(float));
        auto cmp = compare(result.data(), gold_scale_mlp.data.data(), D, 5e-3f);
        INFO("scale_mlp: max_diff=" << cmp.max_diff);
        REQUIRE(cmp.max_diff < 1e-2f);
    }

    ggml_backend_buffer_free(buf);
    ggml_backend_free(backend);
    ggml_free(ctx);
}


SCENARIO("Given GGUF block 0 Attention weights and deterministic input, "
         "when QKV → RoPE → SDPA → Out runs with batch=1, "
         "then output matches PyTorch",
         "[e2e][dit2]") {

    auto* model_path = std::getenv("COSYVOICE_TEST_MODEL");
    if (!model_path) { SKIP("Set COSYVOICE_TEST_MODEL"); return; }

    gold_tensor gold_input, gold_output;
    if (!load_gold("level2_attn_input", gold_input) ||
        !load_gold("level2_attn_output", gold_output)) {
        SKIP("Gold files not found");
        return;
    }

    gguf_file model(model_path);
    REQUIRE(model);

    const char* pfx = "decoder.estimator.transformer_blocks.0.attn";
    auto load_w = [&](const char* suffix) -> ggml_tensor* {
        char name[256];
        snprintf(name, sizeof(name), "%s.%s", pfx, suffix);
        return model.tensor(name);
    };

    auto* qw = load_w("to_q.weight"); auto* qb = load_w("to_q.bias");
    auto* kw = load_w("to_k.weight"); auto* kb = load_w("to_k.bias");
    auto* vw = load_w("to_v.weight"); auto* vb = load_w("to_v.bias");
    auto* ow = load_w("to_out.0.weight"); auto* ob = load_w("to_out.0.bias");
    REQUIRE(qw); REQUIRE(qb); REQUIRE(kw); REQUIRE(kb);
    REQUIRE(vw); REQUIRE(vb); REQUIRE(ow); REQUIRE(ob);

    ggml_init_params params = { .mem_size = 256*1024*1024, .mem_buffer = nullptr, .no_alloc = true };
    auto* ctx = ggml_init(params);

    const int batch = 1;
    auto* x = make_f32(ctx, D, SEQ, batch);
    auto* q_w = make_f32(ctx, qw->ne[0], qw->ne[1]);
    auto* q_b = make_f32(ctx, qb->ne[0]);
    auto* k_w = make_f32(ctx, kw->ne[0], kw->ne[1]);
    auto* k_b = make_f32(ctx, kb->ne[0]);
    auto* v_w = make_f32(ctx, vw->ne[0], vw->ne[1]);
    auto* v_b = make_f32(ctx, vb->ne[0]);
    auto* o_w = make_f32(ctx, ow->ne[0], ow->ne[1]);
    auto* o_b = make_f32(ctx, ob->ne[0]);

    auto* pos_ids = ggml_new_tensor_2d(ctx, GGML_TYPE_I32, SEQ, batch);
    ggml_set_input(pos_ids);

    // QKV
    auto* query = build_linear(ctx, x, q_w, q_b);
    auto* key   = build_linear(ctx, x, k_w, k_b);
    auto* value = build_linear(ctx, x, v_w, v_b);

    // Reshape for RoPE: [head_dim, heads, seq*batch]
    query = ggml_reshape_3d(ctx, query, HD, HEADS, SEQ * batch);
    key   = ggml_reshape_3d(ctx, key,   HD, HEADS, SEQ * batch);
    auto* pos_1d = ggml_reshape_1d(ctx, pos_ids, SEQ * batch);

    query = ggml_rope(ctx, query, pos_1d, HD, GGML_ROPE_TYPE_NORMAL);
    key   = ggml_rope(ctx, key,   pos_1d, HD, GGML_ROPE_TYPE_NORMAL);

    // Reshape for attention: [head_dim, heads, seq, batch]
    query = ggml_reshape_4d(ctx, query, HD, HEADS, SEQ, batch);
    key   = ggml_reshape_4d(ctx, key,   HD, HEADS, SEQ, batch);
    value = ggml_reshape_4d(ctx, value, HD, HEADS, SEQ, batch);

    // Permute: [head_dim, seq, heads, batch]
    query = ggml_permute(ctx, query, 0, 2, 1, 3);
    key   = ggml_permute(ctx, key,   0, 2, 1, 3);
    value = ggml_permute(ctx, value, 0, 2, 1, 3);
    query = ggml_cont(ctx, query);
    key   = ggml_cont(ctx, key);

    // Non-flash attention
    auto* scores = ggml_mul_mat(ctx, key, query);
    scores = ggml_scale(ctx, scores, 1.f / sqrtf((float)HD));
    auto* attn_weights = ggml_soft_max(ctx, scores);
    auto* val_perm = ggml_permute(ctx, value, 1, 0, 2, 3);
    val_perm = ggml_cont(ctx, val_perm);
    auto* attn_out = ggml_mul_mat(ctx, val_perm, attn_weights);
    attn_out = ggml_permute(ctx, attn_out, 0, 2, 1, 3);
    attn_out = ggml_cont(ctx, attn_out);

    // Reshape + output projection
    attn_out = ggml_reshape_3d(ctx, attn_out, D, SEQ, batch);
    auto* out = build_linear(ctx, attn_out, o_w, o_b);
    ggml_set_output(out);

    auto* gf = ggml_new_graph_custom(ctx, 8192, false);
    ggml_build_forward_expand(gf, out);

    auto* backend = ggml_backend_cpu_init();
    auto* buf_alloc = ggml_backend_alloc_ctx_tensors(ctx, backend);
    REQUIRE(buf_alloc);

    fill_from_gguf(q_w, qw); fill_from_gguf(q_b, qb);
    fill_from_gguf(k_w, kw); fill_from_gguf(k_b, kb);
    fill_from_gguf(v_w, vw); fill_from_gguf(v_b, vb);
    fill_from_gguf(o_w, ow); fill_from_gguf(o_b, ob);
    ggml_backend_tensor_set(x, gold_input.data.data(), 0, gold_input.data.size() * sizeof(float));
    {
        std::vector<int32_t> pids(SEQ * batch);
        for (int i = 0; i < SEQ * batch; i++) pids[i] = i % SEQ;
        ggml_backend_tensor_set(pos_ids, pids.data(), 0, pids.size() * sizeof(int32_t));
    }

    REQUIRE(ggml_backend_graph_compute(backend, gf) == GGML_STATUS_SUCCESS);

    THEN("Attention output matches PyTorch") {
        std::vector<float> result(SEQ * D);
        ggml_backend_tensor_get(out, result.data(), 0, result.size() * sizeof(float));
        auto cmp = compare(result.data(), gold_output.data.data(), SEQ * D, 5e-2f);
        INFO("attn: max_diff=" << cmp.max_diff << " mean_abs_diff=" << cmp.mean_abs_diff);
        if (cmp.first_idx >= 0)
            INFO("first mismatch at " << cmp.first_idx
                 << ": got=" << cmp.first_got << " exp=" << cmp.first_exp);
        REQUIRE(cmp.max_diff < 5e-1f);
    }

    ggml_backend_buffer_free(buf_alloc);
    ggml_backend_free(backend);
    ggml_free(ctx);
}


SCENARIO("Given all GGUF block 0 weights and deterministic input, "
         "when full DiTBlock runs (AdaLN → Attn → FF → residual), "
         "then output matches PyTorch",
         "[e2e][dit5]") {

    auto* model_path = std::getenv("COSYVOICE_TEST_MODEL");
    if (!model_path) { SKIP("Set COSYVOICE_TEST_MODEL"); return; }

    gold_tensor gold_x, gold_emb, gold_output;
    if (!load_gold("level5_dit_x", gold_x) ||
        !load_gold("level5_dit_emb", gold_emb) ||
        !load_gold("level5_dit_output", gold_output)) {
        SKIP("Gold files not found");
        return;
    }

    gguf_file model(model_path);
    REQUIRE(model);

    // Load all block 0 weights
    auto T = [&](const char* n) { return model.tensor(n); };
    const char* B = "decoder.estimator.transformer_blocks.0";

    // AdaLayerNormZero
    char buf_n[256];
    #define BT(sub) (snprintf(buf_n, sizeof(buf_n), "%s.%s", B, sub), model.tensor(buf_n))

    auto* aln_w = BT("attn_norm.linear.weight");
    auto* aln_b = BT("attn_norm.linear.bias");
    // Attention
    auto* qw = BT("attn.to_q.weight"); auto* qb = BT("attn.to_q.bias");
    auto* kw = BT("attn.to_k.weight"); auto* kb = BT("attn.to_k.bias");
    auto* vw = BT("attn.to_v.weight"); auto* vb = BT("attn.to_v.bias");
    auto* ow = BT("attn.to_out.0.weight"); auto* ob = BT("attn.to_out.0.bias");
    // FeedForward
    auto* fuw = BT("ff.ff.0.0.weight"); auto* fub = BT("ff.ff.0.0.bias");
    auto* fdw = BT("ff.ff.2.weight");   auto* fdb = BT("ff.ff.2.bias");
    #undef BT

    REQUIRE(aln_w); REQUIRE(aln_b);
    REQUIRE(qw); REQUIRE(qb); REQUIRE(kw); REQUIRE(kb);
    REQUIRE(vw); REQUIRE(vb); REQUIRE(ow); REQUIRE(ob);
    REQUIRE(fuw); REQUIRE(fub); REQUIRE(fdw); REQUIRE(fdb);

    ggml_init_params params = { .mem_size = 512*1024*1024, .mem_buffer = nullptr, .no_alloc = true };
    auto* ctx = ggml_init(params);

    const int batch = 1;

    // Inputs
    auto* x = make_f32(ctx, D, SEQ, batch);
    auto* emb = make_f32(ctx, D);
    auto* pos_ids = ggml_new_tensor_2d(ctx, GGML_TYPE_I32, SEQ, batch);
    ggml_set_input(pos_ids);

    // Allocate weight tensors
    auto mk = [&](ggml_tensor* src) {
        auto* t = make_f32(ctx, src->ne[0], src->ne[1]);
        return t;
    };
    auto mk1 = [&](ggml_tensor* src) {
        auto* t = make_f32(ctx, src->ne[0]);
        return t;
    };

    auto* w_aln_w = mk(aln_w); auto* w_aln_b = mk1(aln_b);
    auto* w_qw = mk(qw); auto* w_qb = mk1(qb);
    auto* w_kw = mk(kw); auto* w_kb = mk1(kb);
    auto* w_vw = mk(vw); auto* w_vb = mk1(vb);
    auto* w_ow = mk(ow); auto* w_ob = mk1(ob);
    auto* w_fuw = mk(fuw); auto* w_fub = mk1(fub);
    auto* w_fdw = mk(fdw); auto* w_fdb = mk1(fdb);

    // ===== Build full DiTBlock graph =====

    // --- AdaLayerNormZero ---
    auto* emb_silu = ggml_silu(ctx, emb);
    auto* emb_proj = build_linear(ctx, emb_silu, w_aln_w, w_aln_b);  // [6*D]

    ggml_tensor* chunks[6];
    split_tensor6(ctx, emb_proj, chunks);
    auto* shift_msa = ggml_cont(ctx, chunks[0]);
    auto* scale_msa = ggml_cont(ctx, chunks[1]);
    auto* gate_msa  = ggml_cont(ctx, chunks[2]);
    auto* shift_mlp = ggml_cont(ctx, chunks[3]);
    auto* scale_mlp = ggml_cont(ctx, chunks[4]);
    auto* gate_mlp  = ggml_cont(ctx, chunks[5]);

    scale_msa = ggml_scale_bias(ctx, scale_msa, 1.f, 1.f);
    scale_mlp = ggml_scale_bias(ctx, scale_mlp, 1.f, 1.f);

    auto* x_norm = ggml_norm(ctx, x, 1e-6f);
    auto* attn_input = ggml_mul(ctx, x_norm, unsqueeze(ctx, scale_msa, 1));
    attn_input = ggml_add(ctx, attn_input, unsqueeze(ctx, shift_msa, 1));

    // --- Attention ---
    auto* query = build_linear(ctx, attn_input, w_qw, w_qb);
    auto* key   = build_linear(ctx, attn_input, w_kw, w_kb);
    auto* value = build_linear(ctx, attn_input, w_vw, w_vb);

    query = ggml_reshape_3d(ctx, query, HD, HEADS, SEQ * batch);
    key   = ggml_reshape_3d(ctx, key,   HD, HEADS, SEQ * batch);
    auto* pos_1d = ggml_reshape_1d(ctx, pos_ids, SEQ * batch);

    query = ggml_rope(ctx, query, pos_1d, HD, GGML_ROPE_TYPE_NORMAL);
    key   = ggml_rope(ctx, key,   pos_1d, HD, GGML_ROPE_TYPE_NORMAL);

    query = ggml_reshape_4d(ctx, query, HD, HEADS, SEQ, batch);
    key   = ggml_reshape_4d(ctx, key,   HD, HEADS, SEQ, batch);
    value = ggml_reshape_4d(ctx, value, HD, HEADS, SEQ, batch);

    query = ggml_cont(ctx, ggml_permute(ctx, query, 0, 2, 1, 3));
    key   = ggml_cont(ctx, ggml_permute(ctx, key,   0, 2, 1, 3));
    value = ggml_permute(ctx, value, 0, 2, 1, 3);

    auto* scores = ggml_mul_mat(ctx, key, query);
    scores = ggml_scale(ctx, scores, 1.f / sqrtf((float)HD));
    auto* attn_w = ggml_soft_max(ctx, scores);
    auto* val_p = ggml_cont(ctx, ggml_permute(ctx, value, 1, 0, 2, 3));
    auto* attn_out = ggml_mul_mat(ctx, val_p, attn_w);
    attn_out = ggml_cont(ctx, ggml_permute(ctx, attn_out, 0, 2, 1, 3));
    attn_out = ggml_reshape_3d(ctx, attn_out, D, SEQ, batch);
    attn_out = build_linear(ctx, attn_out, w_ow, w_ob);

    // Gate + residual
    attn_out = ggml_mul(ctx, attn_out, unsqueeze(ctx, gate_msa, 1));
    auto* x2 = ggml_add(ctx, x, attn_out);

    // --- FeedForward ---
    auto* ff_norm = ggml_norm(ctx, x2, 1e-6f);
    ff_norm = ggml_mul(ctx, ff_norm, unsqueeze(ctx, scale_mlp, 1));
    ff_norm = ggml_add(ctx, ff_norm, unsqueeze(ctx, shift_mlp, 1));

    auto* ff_h = build_linear(ctx, ff_norm, w_fuw, w_fub);
    ff_h = ggml_gelu(ctx, ff_h);
    auto* ff_out = build_linear(ctx, ff_h, w_fdw, w_fdb);
    ff_out = ggml_mul(ctx, ff_out, unsqueeze(ctx, gate_mlp, 1));

    auto* dit_out = ggml_add(ctx, x2, ff_out);
    ggml_set_output(dit_out);

    auto* gf = ggml_new_graph_custom(ctx, 16384, false);
    ggml_build_forward_expand(gf, dit_out);

    auto* backend = ggml_backend_cpu_init();
    auto* buffer = ggml_backend_alloc_ctx_tensors(ctx, backend);
    REQUIRE(buffer);

    // Fill all weights
    fill_from_gguf(w_aln_w, aln_w); fill_from_gguf(w_aln_b, aln_b);
    fill_from_gguf(w_qw, qw); fill_from_gguf(w_qb, qb);
    fill_from_gguf(w_kw, kw); fill_from_gguf(w_kb, kb);
    fill_from_gguf(w_vw, vw); fill_from_gguf(w_vb, vb);
    fill_from_gguf(w_ow, ow); fill_from_gguf(w_ob, ob);
    fill_from_gguf(w_fuw, fuw); fill_from_gguf(w_fub, fub);
    fill_from_gguf(w_fdw, fdw); fill_from_gguf(w_fdb, fdb);

    ggml_backend_tensor_set(x, gold_x.data.data(), 0, gold_x.data.size() * sizeof(float));
    ggml_backend_tensor_set(emb, gold_emb.data.data(), 0, gold_emb.data.size() * sizeof(float));
    {
        std::vector<int32_t> pids(SEQ * batch);
        for (int i = 0; i < SEQ * batch; i++) pids[i] = i % SEQ;
        ggml_backend_tensor_set(pos_ids, pids.data(), 0, pids.size() * sizeof(int32_t));
    }

    REQUIRE(ggml_backend_graph_compute(backend, gf) == GGML_STATUS_SUCCESS);

    THEN("DiTBlock output matches PyTorch") {
        std::vector<float> result(SEQ * D);
        ggml_backend_tensor_get(dit_out, result.data(), 0, result.size() * sizeof(float));
        auto cmp = compare(result.data(), gold_output.data.data(), SEQ * D, 1e-1f);
        INFO("dit_block: max_diff=" << cmp.max_diff
             << " mean_diff=" << cmp.mean_diff
             << " mean_abs_diff=" << cmp.mean_abs_diff);
        if (cmp.first_idx >= 0)
            INFO("first mismatch at " << cmp.first_idx
                 << ": got=" << cmp.first_got << " exp=" << cmp.first_exp);
        // Individual modules pass with Q8_0 error ~ 0.5
        // Full block compounds: expect < 2.0
        REQUIRE(cmp.max_diff < 2.0f);
    }

    ggml_backend_buffer_free(buffer);
    ggml_backend_free(backend);
    ggml_free(ctx);
}
