// Test: InputEmbedding proj with non-zero conditioning, batch=2 CFG.
//
// Gold data generated by: python3 tests/gen_cond_path_gold.py
// Output dir: /tmp/cv_cond_test_gold/
//
// If the proj output matches PyTorch gold, the bug is downstream (DiT blocks).
// If it doesn't match, the bug is in InputEmbedding or tensor layout.

#include <catch2/catch_test_macros.hpp>

#include <ggml.h>
#include <gguf.h>
#include <ggml-backend.h>
#include <ggml-cpu.h>

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <vector>

static const int D        = 1024;
static const int MEL_DIM  = 80;
static const int SEQ      = 20;
static const int BATCH    = 2;

static const char* GOLD_DIR = "/tmp/cv_cond_test_gold";

struct gold_tensor {
    std::vector<int64_t> shape;
    std::vector<float>   data;
    int64_t numel() const { return (int64_t)data.size(); }
};

static bool load_gold(const char* name, gold_tensor& out) {
    std::string path = std::string(GOLD_DIR) + "/" + name + ".bin";
    std::ifstream f(path, std::ios::binary);
    if (!f) return false;
    uint32_t ndim;
    f.read(reinterpret_cast<char*>(&ndim), 4);
    out.shape.resize(ndim);
    for (uint32_t i = 0; i < ndim; i++) {
        int64_t d; f.read(reinterpret_cast<char*>(&d), 8); out.shape[i] = d;
    }
    int64_t n = 1;
    for (auto d : out.shape) n *= d;
    out.data.resize(n);
    f.read(reinterpret_cast<char*>(out.data.data()), n * sizeof(float));
    return f.good();
}

struct gguf_file {
    gguf_context* gguf_ctx = nullptr;
    ggml_context* ggml_ctx = nullptr;
    explicit gguf_file(const char* path) {
        gguf_ctx = gguf_init_from_file(path,
            gguf_init_params{.no_alloc = false, .ctx = &ggml_ctx});
    }
    ~gguf_file() {
        if (gguf_ctx) gguf_free(gguf_ctx);
        if (ggml_ctx) ggml_free(ggml_ctx);
    }
    explicit operator bool() const { return gguf_ctx != nullptr; }
    ggml_tensor* tensor(const char* name) const {
        return ggml_get_tensor(ggml_ctx, name);
    }
};

static void fill_from_gguf(ggml_tensor* dst, ggml_tensor* src) {
    int64_t n = ggml_nelements(src);
    if (src->type == GGML_TYPE_F32) {
        ggml_backend_tensor_set(dst, src->data, 0, n * sizeof(float));
    } else {
        std::vector<float> buf(n);
        ggml_get_type_traits(src->type)->to_float(src->data, buf.data(), n);
        ggml_backend_tensor_set(dst, buf.data(), 0, n * sizeof(float));
    }
}

static ggml_tensor* build_linear(ggml_context* ctx, ggml_tensor* x, ggml_tensor* w, ggml_tensor* b) {
    auto* y = ggml_mul_mat(ctx, w, x);
    if (b) {
        auto* bv = ggml_view_4d(ctx, b, b->ne[0], 1, 1, 1,
                                 b->nb[0], b->nb[0], b->nb[0], 0);
        y = ggml_add(ctx, y, bv);
    }
    return y;
}

static double compare_tensors(const float* result, const float* gold, int64_t n, const char* label) {
    double sum = 0, sum_abs = 0, max_d = 0;
    for (int64_t i = 0; i < n; i++) {
        double d = (double)result[i] - (double)gold[i];
        sum += d;
        sum_abs += std::abs(d);
        max_d = std::max(max_d, std::abs(d));
    }
    printf("  %s: max_diff=%.6f, mean_diff=%.6f, mad=%.6f (n=%lld)\n",
           label, max_d, sum / n, sum_abs / n, (long long)n);
    return max_d;
}


SCENARIO("Given synthetic non-zero conditioning inputs and Q8_0 GGUF weights, "
         "when InputEmbedding.proj runs with batch=2 CFG, "
         "then output matches PyTorch gold",
         "[e2e][cond_path]") {

    auto* model_path = std::getenv("COSYVOICE_TEST_MODEL");
    if (!model_path) { SKIP("Set COSYVOICE_TEST_MODEL"); return; }

    // Load gold
    gold_tensor gold_x, gold_cond, gold_mu, gold_spks;
    gold_tensor gold_ie_proj_output;

    bool gold_ok =
        load_gold("x", gold_x) &&
        load_gold("cond", gold_cond) &&
        load_gold("mu", gold_mu) &&
        load_gold("spks", gold_spks) &&
        load_gold("ie_proj_output", gold_ie_proj_output);

    if (!gold_ok) {
        SKIP("Gold files not found. Run: python3 tests/gen_cond_path_gold.py");
        return;
    }

    printf("Gold loaded.\n");
    // Inputs are saved as PyTorch [S, D] which matches ggml flat layout for ne=[D, S]
    printf("  x: [%lld, %lld]\n", gold_x.shape[0], gold_x.shape[1]);
    printf("  cond: [%lld, %lld]\n", gold_cond.shape[0], gold_cond.shape[1]);
    printf("  mu: [%lld, %lld]\n", gold_mu.shape[0], gold_mu.shape[1]);
    printf("  spks: [%lld, %lld]\n", gold_spks.shape[0], gold_spks.shape[1]);
    printf("  ie_proj_output: ");
    for (auto d : gold_ie_proj_output.shape) printf("%lld ", d);
    printf("(total %lld)\n", gold_ie_proj_output.numel());

    // Load GGUF model weights
    gguf_file model(model_path);
    REQUIRE(bool(model));

    auto* proj_w = model.tensor("decoder.estimator.input_embed.proj.weight");
    auto* proj_b = model.tensor("decoder.estimator.input_embed.proj.bias");
    REQUIRE(proj_w);
    REQUIRE(proj_b);
    printf("  proj.weight: ne=[%lld, %lld], type=%d\n", proj_w->ne[0], proj_w->ne[1], proj_w->type);

    // Build computation graph
    // Inputs (in ggml format: [feature, seq]):
    //   x: [80, 20]
    //   cond: [80, 20]
    //   mu: [80, 20]
    //   spks: [80, 1]
    // For batch=2 CFG: pad cond, mu, spks with zeros (batch[1] = uncond)

    const size_t ctx_size = ggml_tensor_overhead() * 64 + 1024*1024*10;
    ggml_context* ctx = ggml_init({.mem_size = ctx_size, .mem_buffer = nullptr, .no_alloc = true});
    REQUIRE(ctx);

    // Create input tensors
    auto* x_in    = ggml_new_tensor_2d(ctx, GGML_TYPE_F32, MEL_DIM, SEQ);
    auto* cond_in = ggml_new_tensor_2d(ctx, GGML_TYPE_F32, MEL_DIM, SEQ);
    auto* mu_in   = ggml_new_tensor_2d(ctx, GGML_TYPE_F32, MEL_DIM, SEQ);
    auto* spks_in = ggml_new_tensor_2d(ctx, GGML_TYPE_F32, MEL_DIM, 1);
    ggml_set_input(x_in);
    ggml_set_input(cond_in);
    ggml_set_input(mu_in);
    ggml_set_input(spks_in);

    // Create proj weight tensors (match model shapes)
    auto* pw = ggml_new_tensor_2d(ctx, GGML_TYPE_F32, proj_w->ne[0], proj_w->ne[1]);
    auto* pb = ggml_new_tensor_1d(ctx, GGML_TYPE_F32, proj_b->ne[0]);
    ggml_set_input(pw);
    ggml_set_input(pb);

    // --- Build CFG batch=2 graph ---
    // Same as CausalConditionalCFM::prepare_context + DiT::build_cgraph + InputEmbedding

    // Pad for batch=2: original data in batch[0], zeros in batch[1]
    auto* cond_b2 = ggml_pad(ctx, cond_in, 0, 0, 1, 0);  // [80, 20, 2]
    auto* mu_b2   = ggml_pad(ctx, mu_in, 0, 0, 1, 0);     // [80, 20, 2]
    auto* spks_b2 = ggml_pad(ctx, spks_in, 0, 0, 1, 0);   // [80, 1, 2]

    // Repeat x for both batches
    auto* x_b2 = ggml_repeat_4d(ctx, x_in, x_in->ne[0], x_in->ne[1], 2, 1); // [80, 20, 2]

    // InputEmbedding: permute x first (DiT::build_cgraph does this)
    // Wait — x starts as [seq, 80] in the ODE, then DiT permutes to [80, seq].
    // But our x_in is already [80, 20]. DiT::build_cgraph does:
    //   x = ggml_permute(ctx, x, 1, 0, 2, 3);
    // For x = [seq, 80, batch] → [80, seq, batch]
    // But we already have x as [80, seq], so we should NOT permute here.
    // The gold x was saved as [80, 20] from Python (transposed).

    // InputEmbedding::build_cgraph:
    //   spks = ggml_repeat(spks, x)  → [80, 1, 2] → [80, 20, 2]
    //   concat(x, cond, mu, spks) along dim 0 → [320, 20, 2]
    //   proj → [1024, 20, 2]

    auto* spks_rep = ggml_repeat(ctx, spks_b2, x_b2);  // [80, 1, 2] → [80, 20, 2]
    auto* cat = ggml_concat(ctx, x_b2, cond_b2, 0);     // [160, 20, 2]
    cat = ggml_concat(ctx, cat, mu_b2, 0);                // [240, 20, 2]
    cat = ggml_concat(ctx, cat, spks_rep, 0);             // [320, 20, 2]

    auto* proj_out = build_linear(ctx, cat, pw, pb);      // [1024, 20, 2]
    ggml_set_output(proj_out);

    // Build and run graph
    auto* backend = ggml_backend_cpu_init();
    REQUIRE(backend);
    auto* buf = ggml_backend_alloc_ctx_tensors(ctx, backend);
    REQUIRE(buf);

    // Fill inputs from gold data
    // Gold x is [80, 20] which matches ggml ne=[80, 20]
    ggml_backend_tensor_set(x_in, gold_x.data.data(), 0, gold_x.numel() * sizeof(float));
    ggml_backend_tensor_set(cond_in, gold_cond.data.data(), 0, gold_cond.numel() * sizeof(float));
    ggml_backend_tensor_set(mu_in, gold_mu.data.data(), 0, gold_mu.numel() * sizeof(float));
    ggml_backend_tensor_set(spks_in, gold_spks.data.data(), 0, gold_spks.numel() * sizeof(float));

    // Fill proj weights from GGUF
    fill_from_gguf(pw, proj_w);
    ggml_backend_tensor_set(pb, proj_b->data, 0, proj_b->ne[0] * sizeof(float));

    // Build and execute graph
    auto* graph = ggml_new_graph(ctx);
    ggml_build_forward_expand(graph, proj_out);

    auto status = ggml_backend_graph_compute(backend, graph);
    REQUIRE(status == GGML_STATUS_SUCCESS);

    // Read result
    std::vector<float> result(ggml_nelements(proj_out));
    ggml_backend_tensor_get(proj_out, result.data(), 0, result.size() * sizeof(float));

    printf("\nResult proj_out ne=[%lld, %lld, %lld]\n", proj_out->ne[0], proj_out->ne[1], proj_out->ne[2]);

    // Compare against gold
    // Gold ie_proj_output is [2, 20, 1024] in PyTorch layout (B, S, D)
    // ggml result is [1024, 20, 2] (D, S, B)
    // We need to account for the layout difference.
    //
    // In PyTorch: data[b][s][d] = data_flat[b * S * D + s * D + d]
    // In ggml: data[d][s][b] = data_flat[d + s * D + b * S * D]
    // These are actually the SAME flat layout! (C-contiguous in PyTorch = column-major in ggml)
    // Because ggml stores ne[0] contiguously, which is the feature dim.
    // So: ggml[d, s, b] at offset = d + s * 1024 + b * 1024 * 20
    //     PyTorch[b, s, d] at offset = b * 20 * 1024 + s * 1024 + d
    // These are DIFFERENT!
    //
    // ggml flat: iterate d fastest, then s, then b
    // PyTorch flat: iterate d fastest, then s, then b
    // Wait, that IS the same: d + s*D + b*S*D for both.
    // But PyTorch uses b * S * D + s * D + d, which is the same as d + s*D + b*S*D. Yes!
    //
    // So the flat data is the same if we think of ggml ne=[D, S, B] as PyTorch shape=[B, S, D].

    double max_diff = compare_tensors(result.data(), gold_ie_proj_output.data.data(),
                                       result.size(), "ie_proj_output");

    // Print per-batch statistics
    int64_t batch_size = D * SEQ;
    float sum0 = 0, sum1 = 0;
    for (int i = 0; i < batch_size; i++) {
        sum0 += result[i];
        sum1 += result[batch_size + i];
    }
    printf("  batch0 mean=%.6f, batch1 mean=%.6f\n", sum0 / batch_size, sum1 / batch_size);
    printf("  gold: batch0 mean=%.6f, batch1 mean=%.6f\n",
           gold_ie_proj_output.data[0], gold_ie_proj_output.data[1]);  // These are wrong, need proper calc

    // Tolerance: Q8_0 quantization adds ~0.01 error per element
    CHECK(max_diff < 0.5);  // generous threshold for Q8_0

    ggml_backend_buffer_free(buf);
    ggml_backend_free(backend);
    ggml_free(ctx);
}
