// E2E verification: single ODE step with real voice clone data, batch=2 CFG.
//
// Gold data generated by: uv run python gen_e2e_ode_step_gold.py
// Output dir: /tmp/cv_e2e_ode_gold/
//
// This test builds the full pipeline (InputEmbedding proj + 22 DiT blocks +
// norm_out + proj_out + CFG + Euler step) with batch=2 using real dump data
// from the voice clone reproduction. Compares against PyTorch F32 gold.
//
// If this PASSES: the bug is in ODE loop iteration or elsewhere (encoder, HiFT).
// If this FAILS: the bug is in batch=2 CFG graph construction.

#include <catch2/catch_test_macros.hpp>

#include <ggml.h>
#include <gguf.h>
#include <ggml-backend.h>
#include <ggml-cpu.h>

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <string>
#include <vector>

static const int D         = 1024;
static const int HEADS     = 16;
static const int HD        = D / HEADS;
static const int DEPTH     = 22;
static const int MEL_DIM   = 80;
static const int HALF_DIM  = 128;
static const int SUB_SEQ   = 20;
static const int BATCH     = 2;

static const char* GOLD_DIR = "/tmp/cv_e2e_ode_gold";

// --- Helpers (self-contained, same as test_e2e_dit_full.cpp) ---

struct gold_tensor {
    std::vector<int64_t> shape;
    std::vector<float>   data;
    int64_t numel() const { return (int64_t)data.size(); }
};

static bool load_gold(const char* name, gold_tensor& out) {
    std::string path = std::string(GOLD_DIR) + "/" + name + ".bin";
    std::ifstream f(path, std::ios::binary);
    if (!f) return false;
    uint32_t ndim;
    f.read(reinterpret_cast<char*>(&ndim), 4);
    out.shape.resize(ndim);
    for (uint32_t i = 0; i < ndim; i++) {
        int64_t d; f.read(reinterpret_cast<char*>(&d), 8); out.shape[i] = d;
    }
    int64_t n = 1;
    for (auto d : out.shape) n *= d;
    out.data.resize(n);
    f.read(reinterpret_cast<char*>(out.data.data()), n * sizeof(float));
    return f.good();
}

struct gguf_file {
    gguf_context* gguf_ctx = nullptr;
    ggml_context* ggml_ctx = nullptr;
    explicit gguf_file(const char* path) {
        gguf_ctx = gguf_init_from_file(path,
            gguf_init_params{.no_alloc = false, .ctx = &ggml_ctx});
    }
    ~gguf_file() {
        if (gguf_ctx) gguf_free(gguf_ctx);
        if (ggml_ctx) ggml_free(ggml_ctx);
    }
    explicit operator bool() const { return gguf_ctx != nullptr; }
    ggml_tensor* tensor(const char* name) const {
        return ggml_get_tensor(ggml_ctx, name);
    }
    float get_f32(const char* key) const {
        int idx = gguf_find_key(gguf_ctx, key);
        if (idx < 0) return -1.f;
        return gguf_get_val_f32(gguf_ctx, idx);
    }
};

static ggml_tensor* make_f32(ggml_context* ctx, int64_t n0, int64_t n1=1, int64_t n2=1) {
    auto* t = ggml_new_tensor_3d(ctx, GGML_TYPE_F32, n0, n1, n2);
    ggml_set_input(t);
    return t;
}

static void fill_from_gguf(ggml_tensor* dst, ggml_tensor* src) {
    int64_t n = ggml_nelements(src);
    if (src->type == GGML_TYPE_F32) {
        ggml_backend_tensor_set(dst, src->data, 0, n * sizeof(float));
    } else {
        std::vector<float> buf(n);
        ggml_get_type_traits(src->type)->to_float(src->data, buf.data(), n);
        ggml_backend_tensor_set(dst, buf.data(), 0, n * sizeof(float));
    }
}

static ggml_tensor* build_linear(ggml_context* ctx, ggml_tensor* x, ggml_tensor* w, ggml_tensor* b) {
    auto* y = ggml_mul_mat(ctx, w, x);
    if (b) {
        auto* bv = ggml_view_4d(ctx, b, b->ne[0], 1, 1, 1,
                                 b->nb[0], b->nb[0], b->nb[0], 0);
        y = ggml_add(ctx, y, bv);
    }
    return y;
}

static ggml_tensor* unsqueeze(ggml_context* ctx, ggml_tensor* x, int dim) {
    if (dim == 1)
        return ggml_view_4d(ctx, x, x->ne[0], 1, x->ne[1], x->ne[2],
                            x->nb[1], x->nb[1], x->nb[2], 0);
    return x;
}

static void split6(ggml_context* ctx, ggml_tensor* t, ggml_tensor** out) {
    int64_t chunk = t->ne[0] / 6;
    for (int i = 0; i < 6; i++)
        out[i] = ggml_view_1d(ctx, t, chunk, i * chunk * sizeof(float));
}

static void split2(ggml_context* ctx, ggml_tensor* t, ggml_tensor** out) {
    int64_t chunk = t->ne[0] / 2;
    for (int i = 0; i < 2; i++)
        out[i] = ggml_view_1d(ctx, t, chunk, i * chunk * sizeof(float));
}

struct BlockWeights {
    ggml_tensor *aln_w, *aln_b;
    ggml_tensor *qw, *qb, *kw, *kb, *vw, *vb, *ow, *ob;
    ggml_tensor *fuw, *fub, *fdw, *fdb;
};

// Build one DiTBlock graph (parameterized by seq length)
static ggml_tensor* build_dit_block(
    ggml_context* ctx,
    ggml_tensor* x,
    ggml_tensor* emb,
    ggml_tensor* pos_ids,
    const BlockWeights& w,
    int seq, int batch)
{
    // AdaLayerNormZero
    auto* emb_s = ggml_silu(ctx, emb);
    auto* emb_p = build_linear(ctx, emb_s, w.aln_w, w.aln_b);

    ggml_tensor* ch[6];
    split6(ctx, emb_p, ch);
    auto* shift_msa = ggml_cont(ctx, ch[0]);
    auto* scale_msa = ggml_scale_bias(ctx, ggml_cont(ctx, ch[1]), 1.f, 1.f);
    auto* gate_msa  = ggml_cont(ctx, ch[2]);
    auto* shift_mlp = ggml_cont(ctx, ch[3]);
    auto* scale_mlp = ggml_scale_bias(ctx, ggml_cont(ctx, ch[4]), 1.f, 1.f);
    auto* gate_mlp  = ggml_cont(ctx, ch[5]);

    auto* xn = ggml_norm(ctx, x, 1e-6f);
    xn = ggml_mul(ctx, xn, unsqueeze(ctx, scale_msa, 1));
    xn = ggml_add(ctx, xn, unsqueeze(ctx, shift_msa, 1));

    // Attention
    auto* q = build_linear(ctx, xn, w.qw, w.qb);
    auto* k = build_linear(ctx, xn, w.kw, w.kb);
    auto* v = build_linear(ctx, xn, w.vw, w.vb);

    q = ggml_reshape_3d(ctx, q, HD, HEADS, seq * batch);
    k = ggml_reshape_3d(ctx, k, HD, HEADS, seq * batch);
    auto* pos_1d = ggml_reshape_1d(ctx, pos_ids, seq * batch);

    q = ggml_rope(ctx, q, pos_1d, HD, GGML_ROPE_TYPE_NORMAL);
    k = ggml_rope(ctx, k, pos_1d, HD, GGML_ROPE_TYPE_NORMAL);

    q = ggml_reshape_4d(ctx, q, HD, HEADS, seq, batch);
    k = ggml_reshape_4d(ctx, k, HD, HEADS, seq, batch);
    v = ggml_reshape_4d(ctx, v, HD, HEADS, seq, batch);

    q = ggml_cont(ctx, ggml_permute(ctx, q, 0, 2, 1, 3));
    k = ggml_cont(ctx, ggml_permute(ctx, k, 0, 2, 1, 3));
    v = ggml_permute(ctx, v, 0, 2, 1, 3);

    auto* scores = ggml_scale(ctx, ggml_mul_mat(ctx, k, q), 1.f / sqrtf((float)HD));
    auto* attn_w = ggml_soft_max(ctx, scores);
    auto* vp = ggml_cont(ctx, ggml_permute(ctx, v, 1, 0, 2, 3));
    auto* attn_out = ggml_cont(ctx, ggml_permute(ctx, ggml_mul_mat(ctx, vp, attn_w), 0, 2, 1, 3));
    attn_out = ggml_reshape_3d(ctx, attn_out, D, seq, batch);
    attn_out = build_linear(ctx, attn_out, w.ow, w.ob);

    attn_out = ggml_mul(ctx, attn_out, unsqueeze(ctx, gate_msa, 1));
    x = ggml_add(ctx, x, attn_out);

    // FeedForward
    auto* fn = ggml_norm(ctx, x, 1e-6f);
    fn = ggml_mul(ctx, fn, unsqueeze(ctx, scale_mlp, 1));
    fn = ggml_add(ctx, fn, unsqueeze(ctx, shift_mlp, 1));
    auto* ff = ggml_gelu(ctx, build_linear(ctx, fn, w.fuw, w.fub));
    ff = build_linear(ctx, ff, w.fdw, w.fdb);
    ff = ggml_mul(ctx, ff, unsqueeze(ctx, gate_mlp, 1));
    x = ggml_add(ctx, x, ff);

    return x;
}

// Compare helper: returns max absolute difference, prints stats
static double compare_tensors(const float* result, const float* gold, int64_t n, const char* label) {
    double sum = 0, sum_abs = 0, max_d = 0;
    for (int64_t i = 0; i < n; i++) {
        double d = (double)result[i] - (double)gold[i];
        sum += d;
        sum_abs += std::abs(d);
        max_d = std::max(max_d, std::abs(d));
    }
    double mean_diff = sum / n;
    double mad = sum_abs / n;
    printf("  %s: max_diff=%.6f, mean_diff=%.6f, mad=%.6f\n", label, max_d, mean_diff, mad);
    return max_d;
}


SCENARIO("Given real voice clone data and Q8_0 GGUF weights, "
         "when a single ODE step runs with batch=2 CFG pipeline, "
         "then Euler step output matches PyTorch gold",
         "[e2e][ode_step]") {

    auto* model_path = std::getenv("COSYVOICE_TEST_MODEL");
    if (!model_path) { SKIP("Set COSYVOICE_TEST_MODEL"); return; }

    // Load all gold files
    gold_tensor gold_x_old, gold_mu, gold_time_emb, gold_ie_output;
    gold_tensor gold_dphi_cond, gold_dphi_uncond, gold_dphi_final, gold_x_new;

    bool gold_ok =
        load_gold("ode_step2_x_old", gold_x_old) &&
        load_gold("ode_step2_mu", gold_mu) &&
        load_gold("ode_step2_time_emb", gold_time_emb) &&
        load_gold("ode_step2_ie_output", gold_ie_output) &&
        load_gold("ode_step2_dphi_cond", gold_dphi_cond) &&
        load_gold("ode_step2_dphi_uncond", gold_dphi_uncond) &&
        load_gold("ode_step2_dphi_final", gold_dphi_final) &&
        load_gold("ode_step2_x_new", gold_x_new);

    if (!gold_ok) {
        SKIP("Gold files not found. Run: cd tests && uv run python gen_e2e_ode_step_gold.py");
        return;
    }

    printf("Gold loaded: x_old=%lld, mu=%lld, time_emb=%lld, ie_output=%lld\n",
           gold_x_old.numel(), gold_mu.numel(), gold_time_emb.numel(), gold_ie_output.numel());

    // Load GGUF model
    gguf_file model(model_path);
    REQUIRE(model);

    // Read cfg_rate from model metadata
    float cfg_rate = model.get_f32("decoder.inference_cfg_rate");
    if (cfg_rate < 0.f) cfg_rate = 0.7f;
    printf("cfg_rate=%.4f\n", cfg_rate);

    // Compute t_span (cosine schedule)
    std::vector<float> t_span(11);
    for (int i = 0; i < 11; i++)
        t_span[i] = 1.f - std::cos(0.1f * 0.5f * (float)M_PI * (float)i);
    float t_val = t_span[1];
    float dt_val = t_span[2] - t_span[1];
    printf("step2: t=%.6f, dt=%.6f\n", t_val, dt_val);

    // --- Allocate ggml context ---
    ggml_init_params params = {
        .mem_size = (size_t)4096 * 1024 * 1024,
        .mem_buffer = nullptr,
        .no_alloc = true,
    };
    auto* ctx = ggml_init(params);
    REQUIRE(ctx);

    // --- Create input tensors ---

    // Timestep embedding inputs
    auto* t_scalar = make_f32(ctx, 1);
    auto* emb_coeff = make_f32(ctx, HALF_DIM);

    // Mel inputs [MEL_DIM, SUB_SEQ, BATCH]
    auto* x_mel    = make_f32(ctx, MEL_DIM, SUB_SEQ, BATCH);
    auto* mu_mel   = make_f32(ctx, MEL_DIM, SUB_SEQ, BATCH);
    auto* cond_mel = make_f32(ctx, MEL_DIM, SUB_SEQ, BATCH);
    auto* spks_mel = make_f32(ctx, MEL_DIM, SUB_SEQ, BATCH);

    // Position IDs [SUB_SEQ, BATCH]
    auto* pos_ids = ggml_new_tensor_2d(ctx, GGML_TYPE_I32, SUB_SEQ, BATCH);
    ggml_set_input(pos_ids);

    // --- Load weights from GGUF ---

    // InputEmbedding proj
    auto* ie_pw_gguf = model.tensor("decoder.estimator.input_embed.proj.weight");
    auto* ie_pb_gguf = model.tensor("decoder.estimator.input_embed.proj.bias");
    REQUIRE(ie_pw_gguf); REQUIRE(ie_pb_gguf);
    auto* ie_pw = make_f32(ctx, ie_pw_gguf->ne[0], ie_pw_gguf->ne[1]);
    auto* ie_pb = make_f32(ctx, ie_pb_gguf->ne[0]);

    // TimestepEmbedding MLP
    auto* tml0_w_gguf = model.tensor("decoder.estimator.time_embed.time_mlp.0.weight");
    auto* tml0_b_gguf = model.tensor("decoder.estimator.time_embed.time_mlp.0.bias");
    auto* tml2_w_gguf = model.tensor("decoder.estimator.time_embed.time_mlp.2.weight");
    auto* tml2_b_gguf = model.tensor("decoder.estimator.time_embed.time_mlp.2.bias");
    REQUIRE(tml0_w_gguf); REQUIRE(tml0_b_gguf);
    REQUIRE(tml2_w_gguf); REQUIRE(tml2_b_gguf);
    auto* tml0_w = make_f32(ctx, tml0_w_gguf->ne[0], tml0_w_gguf->ne[1]);
    auto* tml0_b = make_f32(ctx, tml0_b_gguf->ne[0]);
    auto* tml2_w = make_f32(ctx, tml2_w_gguf->ne[0], tml2_w_gguf->ne[1]);
    auto* tml2_b = make_f32(ctx, tml2_b_gguf->ne[0]);

    // 22 DiT block weights
    std::vector<BlockWeights> bw(DEPTH), bw_gguf(DEPTH);
    for (int i = 0; i < DEPTH; i++) {
        char pfx[128];
        #define LOAD(field, suffix) do { \
            snprintf(pfx, sizeof(pfx), "decoder.estimator.transformer_blocks.%d.%s", i, suffix); \
            bw_gguf[i].field = model.tensor(pfx); \
            REQUIRE(bw_gguf[i].field != nullptr); \
            bw[i].field = make_f32(ctx, bw_gguf[i].field->ne[0], \
                bw_gguf[i].field->ne[1] > 1 ? bw_gguf[i].field->ne[1] : 1); \
        } while(0)

        LOAD(aln_w, "attn_norm.linear.weight");
        LOAD(aln_b, "attn_norm.linear.bias");
        LOAD(qw, "attn.to_q.weight"); LOAD(qb, "attn.to_q.bias");
        LOAD(kw, "attn.to_k.weight"); LOAD(kb, "attn.to_k.bias");
        LOAD(vw, "attn.to_v.weight"); LOAD(vb, "attn.to_v.bias");
        LOAD(ow, "attn.to_out.0.weight"); LOAD(ob, "attn.to_out.0.bias");
        LOAD(fuw, "ff.ff.0.0.weight"); LOAD(fub, "ff.ff.0.0.bias");
        LOAD(fdw, "ff.ff.2.weight"); LOAD(fdb, "ff.ff.2.bias");
        #undef LOAD
    }

    // norm_out + proj_out
    auto* no_w_gguf = model.tensor("decoder.estimator.norm_out.linear.weight");
    auto* no_b_gguf = model.tensor("decoder.estimator.norm_out.linear.bias");
    auto* po_w_gguf = model.tensor("decoder.estimator.proj_out.weight");
    auto* po_b_gguf = model.tensor("decoder.estimator.proj_out.bias");
    REQUIRE(no_w_gguf); REQUIRE(no_b_gguf);
    REQUIRE(po_w_gguf); REQUIRE(po_b_gguf);
    auto* no_w = make_f32(ctx, no_w_gguf->ne[0], no_w_gguf->ne[1]);
    auto* no_b = make_f32(ctx, no_b_gguf->ne[0]);
    auto* po_w = make_f32(ctx, po_w_gguf->ne[0], po_w_gguf->ne[1]);
    auto* po_b = make_f32(ctx, po_b_gguf->ne[0]);

    // --- Build graph ---

    // A. Timestep embedding: t → sinusoidal [256] → MLP → [1024]
    auto* t_rep = ggml_repeat(ctx, t_scalar, emb_coeff);  // [128]
    auto* t_mul = ggml_mul(ctx, t_rep, emb_coeff);         // [128]
    auto* sin_part = ggml_sin(ctx, t_mul);                  // [128]
    auto* cos_part = ggml_cos(ctx, t_mul);                  // [128]
    auto* sinpos = ggml_concat(ctx, sin_part, cos_part, 0); // [256]

    auto* time_emb = build_linear(ctx, sinpos, tml0_w, tml0_b); // [1024]
    time_emb = ggml_silu(ctx, time_emb);
    time_emb = build_linear(ctx, time_emb, tml2_w, tml2_b);     // [1024]
    ggml_set_name(time_emb, "time_emb");
    ggml_set_output(time_emb);

    // B. InputEmbedding: concat features along dim 0
    // x_mel[80,20,2], cond_mel[80,20,2], mu_mel[80,20,2], spks_mel[80,20,2]
    auto* ie_input = ggml_concat(ctx, x_mel, cond_mel, 0);    // [160,20,2]
    ie_input = ggml_concat(ctx, ie_input, mu_mel, 0);          // [240,20,2]
    ie_input = ggml_concat(ctx, ie_input, spks_mel, 0);        // [320,20,2]

    // proj: [320,20,2] → [1024,20,2]
    auto* ie_output = build_linear(ctx, ie_input, ie_pw, ie_pb);
    ggml_set_name(ie_output, "ie_output");
    ggml_set_output(ie_output);

    // C. 22 DiT blocks
    auto* cur = ie_output;
    for (int i = 0; i < DEPTH; i++) {
        cur = build_dit_block(ctx, cur, time_emb, pos_ids, bw[i], SUB_SEQ, BATCH);
    }

    // D. AdaLayerNorm_Final
    auto* emb_final = ggml_silu(ctx, time_emb);
    emb_final = build_linear(ctx, emb_final, no_w, no_b);
    ggml_tensor* final_ch[2];
    split2(ctx, emb_final, final_ch);
    auto* f_scale = ggml_scale_bias(ctx, ggml_cont(ctx, final_ch[0]), 1.f, 1.f);
    auto* f_shift = ggml_cont(ctx, final_ch[1]);

    cur = ggml_norm(ctx, cur, 1e-6f);
    cur = ggml_mul(ctx, cur, unsqueeze(ctx, f_scale, 1));
    cur = ggml_add(ctx, cur, unsqueeze(ctx, f_shift, 1));

    // proj_out: [1024,20,2] → [80,20,2]
    auto* dit_out = build_linear(ctx, cur, po_w, po_b);
    ggml_set_name(dit_out, "dit_out");
    ggml_set_output(dit_out);

    // E. Split batch → CFG
    auto* dphi_cond_t = ggml_view_3d(ctx, dit_out, MEL_DIM, SUB_SEQ, 1,
        dit_out->nb[1], dit_out->nb[2], 0);
    auto* dphi_uncond_t = ggml_view_3d(ctx, dit_out, MEL_DIM, SUB_SEQ, 1,
        dit_out->nb[1], dit_out->nb[2], dit_out->nb[2]);

    dphi_cond_t = ggml_cont(ctx, dphi_cond_t);
    dphi_uncond_t = ggml_cont(ctx, dphi_uncond_t);
    ggml_set_name(dphi_cond_t, "dphi_cond");
    ggml_set_name(dphi_uncond_t, "dphi_uncond");
    ggml_set_output(dphi_cond_t);
    ggml_set_output(dphi_uncond_t);

    // F. CFG: (1+cfg)*cond - cfg*uncond
    auto* dphi_final = ggml_sub(ctx,
        ggml_scale(ctx, dphi_cond_t, 1.f + cfg_rate),
        ggml_scale(ctx, dphi_uncond_t, cfg_rate));
    ggml_set_name(dphi_final, "dphi_final");
    ggml_set_output(dphi_final);

    // G. Euler step: x_new = x_old + dt * dphi_final
    // x_old is batch 0 of x_mel
    auto* x_old_t = ggml_view_3d(ctx, x_mel, MEL_DIM, SUB_SEQ, 1,
        x_mel->nb[1], x_mel->nb[2], 0);
    x_old_t = ggml_cont(ctx, x_old_t);
    auto* x_new_t = ggml_add(ctx, x_old_t, ggml_scale(ctx, dphi_final, dt_val));
    ggml_set_name(x_new_t, "x_new");
    ggml_set_output(x_new_t);

    // Build graph
    auto* gf = ggml_new_graph_custom(ctx, 262144, false);
    ggml_build_forward_expand(gf, x_new_t);

    // --- Allocate backend ---
    auto* backend = ggml_backend_cpu_init();
    REQUIRE(backend);
    auto* buf = ggml_backend_alloc_ctx_tensors(ctx, backend);
    REQUIRE(buf);

    // --- Fill weights from GGUF ---
    fill_from_gguf(ie_pw, ie_pw_gguf);
    fill_from_gguf(ie_pb, ie_pb_gguf);
    fill_from_gguf(tml0_w, tml0_w_gguf);
    fill_from_gguf(tml0_b, tml0_b_gguf);
    fill_from_gguf(tml2_w, tml2_w_gguf);
    fill_from_gguf(tml2_b, tml2_b_gguf);

    for (int i = 0; i < DEPTH; i++) {
        fill_from_gguf(bw[i].aln_w, bw_gguf[i].aln_w);
        fill_from_gguf(bw[i].aln_b, bw_gguf[i].aln_b);
        fill_from_gguf(bw[i].qw, bw_gguf[i].qw);
        fill_from_gguf(bw[i].qb, bw_gguf[i].qb);
        fill_from_gguf(bw[i].kw, bw_gguf[i].kw);
        fill_from_gguf(bw[i].kb, bw_gguf[i].kb);
        fill_from_gguf(bw[i].vw, bw_gguf[i].vw);
        fill_from_gguf(bw[i].vb, bw_gguf[i].vb);
        fill_from_gguf(bw[i].ow, bw_gguf[i].ow);
        fill_from_gguf(bw[i].ob, bw_gguf[i].ob);
        fill_from_gguf(bw[i].fuw, bw_gguf[i].fuw);
        fill_from_gguf(bw[i].fub, bw_gguf[i].fub);
        fill_from_gguf(bw[i].fdw, bw_gguf[i].fdw);
        fill_from_gguf(bw[i].fdb, bw_gguf[i].fdb);
    }

    fill_from_gguf(no_w, no_w_gguf);
    fill_from_gguf(no_b, no_b_gguf);
    fill_from_gguf(po_w, po_w_gguf);
    fill_from_gguf(po_b, po_b_gguf);

    // --- Fill input tensors ---

    // t_scalar = t_span[1]
    ggml_backend_tensor_set(t_scalar, &t_val, 0, sizeof(float));

    // emb_coeff: exp(i * -log(10000) / (HALF_DIM-1)) * 1000
    {
        std::vector<float> coeff(HALF_DIM);
        for (int i = 0; i < HALF_DIM; i++)
            coeff[i] = std::exp((float)i * (-std::log(10000.f) / (HALF_DIM - 1))) * 1000.f;
        ggml_backend_tensor_set(emb_coeff, coeff.data(), 0, coeff.size() * sizeof(float));
    }

    // x_mel: batch 0 = gold x_old, batch 1 = gold x_old (x is repeated in CFG)
    {
        size_t batch_bytes = MEL_DIM * SUB_SEQ * sizeof(float);
        ggml_backend_tensor_set(x_mel, gold_x_old.data.data(), 0, batch_bytes);
        ggml_backend_tensor_set(x_mel, gold_x_old.data.data(), batch_bytes, batch_bytes);
    }

    // mu_mel: batch 0 = gold mu, batch 1 = zeros
    {
        size_t batch_bytes = MEL_DIM * SUB_SEQ * sizeof(float);
        ggml_backend_tensor_set(mu_mel, gold_mu.data.data(), 0, batch_bytes);
        std::vector<float> zeros(MEL_DIM * SUB_SEQ, 0.f);
        ggml_backend_tensor_set(mu_mel, zeros.data(), batch_bytes, batch_bytes);
    }

    // cond_mel, spks_mel: all zeros
    {
        std::vector<float> zeros(MEL_DIM * SUB_SEQ * BATCH, 0.f);
        ggml_backend_tensor_set(cond_mel, zeros.data(), 0, zeros.size() * sizeof(float));
        ggml_backend_tensor_set(spks_mel, zeros.data(), 0, zeros.size() * sizeof(float));
    }

    // pos_ids: [0,1,...,SUB_SEQ-1] repeated for both batches
    {
        std::vector<int32_t> pids(SUB_SEQ * BATCH);
        for (int i = 0; i < SUB_SEQ * BATCH; i++) pids[i] = i % SUB_SEQ;
        ggml_backend_tensor_set(pos_ids, pids.data(), 0, pids.size() * sizeof(int32_t));
    }

    // --- Compute ---
    printf("Computing batch=2 CFG pipeline (22 DiT blocks, SUB_SEQ=%d)...\n", SUB_SEQ);
    auto status = ggml_backend_graph_compute(backend, gf);
    REQUIRE(status == GGML_STATUS_SUCCESS);
    printf("Graph compute done.\n");

    // --- Extract and compare results ---

    THEN("timestep embedding matches PyTorch") {
        std::vector<float> result(D);
        ggml_backend_tensor_get(time_emb, result.data(), 0, D * sizeof(float));
        auto md = compare_tensors(result.data(), gold_time_emb.data.data(), D, "time_emb");
        REQUIRE(md < 0.05);
    }

    THEN("InputEmbedding output matches PyTorch") {
        std::vector<float> result(D * SUB_SEQ * BATCH);
        ggml_backend_tensor_get(ie_output, result.data(), 0, result.size() * sizeof(float));
        // Gold ie_output is [2, SUB_SEQ, D] in PyTorch C-order = [D, SUB_SEQ, 2] in ggml F-order
        // Both store data in the same flat order, so direct comparison works
        auto md = compare_tensors(result.data(), gold_ie_output.data.data(),
                                  D * SUB_SEQ * BATCH, "ie_output");
        REQUIRE(md < 1.0);
    }

    THEN("dphi_cond matches PyTorch within Q8_0 tolerance") {
        std::vector<float> result(MEL_DIM * SUB_SEQ);
        ggml_backend_tensor_get(dphi_cond_t, result.data(), 0, result.size() * sizeof(float));
        auto md = compare_tensors(result.data(), gold_dphi_cond.data.data(),
                                  MEL_DIM * SUB_SEQ, "dphi_cond");
        INFO("(22 Q8_0 blocks, batch=2 — large error expected from quantization)");
        REQUIRE(md < 500.0);
    }

    THEN("dphi_uncond matches PyTorch within Q8_0 tolerance") {
        std::vector<float> result(MEL_DIM * SUB_SEQ);
        ggml_backend_tensor_get(dphi_uncond_t, result.data(), 0, result.size() * sizeof(float));
        auto md = compare_tensors(result.data(), gold_dphi_uncond.data.data(),
                                  MEL_DIM * SUB_SEQ, "dphi_uncond");
        REQUIRE(md < 500.0);
    }

    THEN("CFG dphi_final matches PyTorch") {
        std::vector<float> result(MEL_DIM * SUB_SEQ);
        ggml_backend_tensor_get(dphi_final, result.data(), 0, result.size() * sizeof(float));
        auto md = compare_tensors(result.data(), gold_dphi_final.data.data(),
                                  MEL_DIM * SUB_SEQ, "dphi_final");
        REQUIRE(md < 500.0);
    }

    THEN("Euler step x_new matches PyTorch (KEY diagnostic)") {
        std::vector<float> result(MEL_DIM * SUB_SEQ);
        ggml_backend_tensor_get(x_new_t, result.data(), 0, result.size() * sizeof(float));
        auto md = compare_tensors(result.data(), gold_x_new.data.data(),
                                  MEL_DIM * SUB_SEQ, "x_new");
        INFO("dt=" << dt_val << " shrinks dphi error; if this fails, pipeline integration is broken");
        REQUIRE(md < 10.0);
    }

    ggml_backend_buffer_free(buf);
    ggml_backend_free(backend);
    ggml_free(ctx);
}
