// E2E verification: full 10-step ODE loop (steps 2-10) vs PyTorch gold.
//
// Gold data generated by: uv run python gen_e2e_ode_full_gold.py
// Output dir: /tmp/cv_e2e_ode_full_gold/
//
// Tests two patterns:
//   [correct]   — each step uses correct t/dt from cosine schedule
//   [prodmatch] — step 2 uses step 1's t/dt (cosyvoice-tts.cpp:358 bug)
//
// Graph is built once, then t and dt are patched via op_params per step
// (same pattern as production token2wav).

#include <catch2/catch_test_macros.hpp>

#include <ggml.h>
#include <gguf.h>
#include <ggml-backend.h>
#include <ggml-cpu.h>

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <string>
#include <vector>

static const int D         = 1024;
static const int HEADS     = 16;
static const int HD        = D / HEADS;
static const int DEPTH     = 22;
static const int MEL_DIM   = 80;
static const int HALF_DIM  = 128;
static const int SUB_SEQ   = 20;
static const int BATCH     = 2;
static const int N_STEPS   = 11;  // t_span size (steps 1..10)

static const char* GOLD_DIR = "/tmp/cv_e2e_ode_full_gold";

// --- Helpers (self-contained) ---

struct gold_tensor {
    std::vector<int64_t> shape;
    std::vector<float>   data;
    int64_t numel() const { return (int64_t)data.size(); }
};

static bool load_gold(const char* name, gold_tensor& out) {
    std::string path = std::string(GOLD_DIR) + "/" + name + ".bin";
    std::ifstream f(path, std::ios::binary);
    if (!f) return false;
    uint32_t ndim;
    f.read(reinterpret_cast<char*>(&ndim), 4);
    out.shape.resize(ndim);
    for (uint32_t i = 0; i < ndim; i++) {
        int64_t d; f.read(reinterpret_cast<char*>(&d), 8); out.shape[i] = d;
    }
    int64_t n = 1;
    for (auto d : out.shape) n *= d;
    out.data.resize(n);
    f.read(reinterpret_cast<char*>(out.data.data()), n * sizeof(float));
    return f.good();
}

struct gguf_file {
    gguf_context* gguf_ctx = nullptr;
    ggml_context* ggml_ctx = nullptr;
    explicit gguf_file(const char* path) {
        gguf_ctx = gguf_init_from_file(path,
            gguf_init_params{.no_alloc = false, .ctx = &ggml_ctx});
    }
    ~gguf_file() {
        if (gguf_ctx) gguf_free(gguf_ctx);
        if (ggml_ctx) ggml_free(ggml_ctx);
    }
    explicit operator bool() const { return gguf_ctx != nullptr; }
    ggml_tensor* tensor(const char* name) const {
        return ggml_get_tensor(ggml_ctx, name);
    }
    float get_f32(const char* key) const {
        int idx = gguf_find_key(gguf_ctx, key);
        if (idx < 0) return -1.f;
        return gguf_get_val_f32(gguf_ctx, idx);
    }
};

static ggml_tensor* make_f32(ggml_context* ctx, int64_t n0, int64_t n1=1, int64_t n2=1) {
    auto* t = ggml_new_tensor_3d(ctx, GGML_TYPE_F32, n0, n1, n2);
    ggml_set_input(t);
    return t;
}

static void fill_from_gguf(ggml_tensor* dst, ggml_tensor* src) {
    int64_t n = ggml_nelements(src);
    if (src->type == GGML_TYPE_F32) {
        ggml_backend_tensor_set(dst, src->data, 0, n * sizeof(float));
    } else {
        std::vector<float> buf(n);
        ggml_get_type_traits(src->type)->to_float(src->data, buf.data(), n);
        ggml_backend_tensor_set(dst, buf.data(), 0, n * sizeof(float));
    }
}

static ggml_tensor* build_linear(ggml_context* ctx, ggml_tensor* x, ggml_tensor* w, ggml_tensor* b) {
    auto* y = ggml_mul_mat(ctx, w, x);
    if (b) {
        auto* bv = ggml_view_4d(ctx, b, b->ne[0], 1, 1, 1,
                                 b->nb[0], b->nb[0], b->nb[0], 0);
        y = ggml_add(ctx, y, bv);
    }
    return y;
}

static ggml_tensor* unsqueeze(ggml_context* ctx, ggml_tensor* x, int dim) {
    if (dim == 1)
        return ggml_view_4d(ctx, x, x->ne[0], 1, x->ne[1], x->ne[2],
                            x->nb[1], x->nb[1], x->nb[2], 0);
    return x;
}

static void split6(ggml_context* ctx, ggml_tensor* t, ggml_tensor** out) {
    int64_t chunk = t->ne[0] / 6;
    for (int i = 0; i < 6; i++)
        out[i] = ggml_view_1d(ctx, t, chunk, i * chunk * sizeof(float));
}

static void split2(ggml_context* ctx, ggml_tensor* t, ggml_tensor** out) {
    int64_t chunk = t->ne[0] / 2;
    for (int i = 0; i < 2; i++)
        out[i] = ggml_view_1d(ctx, t, chunk, i * chunk * sizeof(float));
}

struct BlockWeights {
    ggml_tensor *aln_w, *aln_b;
    ggml_tensor *qw, *qb, *kw, *kb, *vw, *vb, *ow, *ob;
    ggml_tensor *fuw, *fub, *fdw, *fdb;
};

static ggml_tensor* build_dit_block(
    ggml_context* ctx, ggml_tensor* x, ggml_tensor* emb, ggml_tensor* pos_ids,
    const BlockWeights& w, int seq, int batch)
{
    auto* emb_s = ggml_silu(ctx, emb);
    auto* emb_p = build_linear(ctx, emb_s, w.aln_w, w.aln_b);

    ggml_tensor* ch[6];
    split6(ctx, emb_p, ch);
    auto* shift_msa = ggml_cont(ctx, ch[0]);
    auto* scale_msa = ggml_scale_bias(ctx, ggml_cont(ctx, ch[1]), 1.f, 1.f);
    auto* gate_msa  = ggml_cont(ctx, ch[2]);
    auto* shift_mlp = ggml_cont(ctx, ch[3]);
    auto* scale_mlp = ggml_scale_bias(ctx, ggml_cont(ctx, ch[4]), 1.f, 1.f);
    auto* gate_mlp  = ggml_cont(ctx, ch[5]);

    auto* xn = ggml_norm(ctx, x, 1e-6f);
    xn = ggml_mul(ctx, xn, unsqueeze(ctx, scale_msa, 1));
    xn = ggml_add(ctx, xn, unsqueeze(ctx, shift_msa, 1));

    auto* q = build_linear(ctx, xn, w.qw, w.qb);
    auto* k = build_linear(ctx, xn, w.kw, w.kb);
    auto* v = build_linear(ctx, xn, w.vw, w.vb);

    q = ggml_reshape_3d(ctx, q, HD, HEADS, seq * batch);
    k = ggml_reshape_3d(ctx, k, HD, HEADS, seq * batch);
    auto* pos_1d = ggml_reshape_1d(ctx, pos_ids, seq * batch);

    q = ggml_rope(ctx, q, pos_1d, HD, GGML_ROPE_TYPE_NORMAL);
    k = ggml_rope(ctx, k, pos_1d, HD, GGML_ROPE_TYPE_NORMAL);

    q = ggml_reshape_4d(ctx, q, HD, HEADS, seq, batch);
    k = ggml_reshape_4d(ctx, k, HD, HEADS, seq, batch);
    v = ggml_reshape_4d(ctx, v, HD, HEADS, seq, batch);

    q = ggml_cont(ctx, ggml_permute(ctx, q, 0, 2, 1, 3));
    k = ggml_cont(ctx, ggml_permute(ctx, k, 0, 2, 1, 3));
    v = ggml_permute(ctx, v, 0, 2, 1, 3);

    auto* scores = ggml_scale(ctx, ggml_mul_mat(ctx, k, q), 1.f / sqrtf((float)HD));
    auto* attn_w = ggml_soft_max(ctx, scores);
    auto* vp = ggml_cont(ctx, ggml_permute(ctx, v, 1, 0, 2, 3));
    auto* attn_out = ggml_cont(ctx, ggml_permute(ctx, ggml_mul_mat(ctx, vp, attn_w), 0, 2, 1, 3));
    attn_out = ggml_reshape_3d(ctx, attn_out, D, seq, batch);
    attn_out = build_linear(ctx, attn_out, w.ow, w.ob);

    attn_out = ggml_mul(ctx, attn_out, unsqueeze(ctx, gate_msa, 1));
    x = ggml_add(ctx, x, attn_out);

    auto* fn = ggml_norm(ctx, x, 1e-6f);
    fn = ggml_mul(ctx, fn, unsqueeze(ctx, scale_mlp, 1));
    fn = ggml_add(ctx, fn, unsqueeze(ctx, shift_mlp, 1));
    auto* ff = ggml_gelu(ctx, build_linear(ctx, fn, w.fuw, w.fub));
    ff = build_linear(ctx, ff, w.fdw, w.fdb);
    ff = ggml_mul(ctx, ff, unsqueeze(ctx, gate_mlp, 1));
    x = ggml_add(ctx, x, ff);

    return x;
}

static double compare_tensors(const float* result, const float* gold, int64_t n, const char* label) {
    double sum = 0, sum_abs = 0, max_d = 0;
    for (int64_t i = 0; i < n; i++) {
        double d = (double)result[i] - (double)gold[i];
        sum += d;
        sum_abs += std::abs(d);
        max_d = std::max(max_d, std::abs(d));
    }
    printf("  %s: max_diff=%.6f, mean_diff=%.6f, mad=%.6f\n",
           label, max_d, sum / n, sum_abs / n);
    return max_d;
}

static float tensor_mean(const float* data, int64_t n) {
    double sum = 0;
    for (int64_t i = 0; i < n; i++) sum += data[i];
    return (float)(sum / n);
}

// Compute cosine t_span schedule (matching C++ get_t_and_dt)
static void get_t_and_dt(const std::vector<float>& t_span, int step, float& t, float& dt) {
    t = t_span[0];
    for (int cur = 1; cur < step; cur++)
        t += t_span[cur] - t_span[cur - 1];
    dt = t_span[step] - t_span[step - 1];
}

// Shared structure for the full ODE test context
struct OdeTestContext {
    // ggml resources
    ggml_context*        ctx = nullptr;
    ggml_backend_t       backend = nullptr;
    ggml_backend_buffer* buf = nullptr;

    // Input tensors (patched per step)
    ggml_tensor* t_scalar = nullptr;
    ggml_tensor* emb_coeff = nullptr;
    ggml_tensor* x_mel = nullptr;
    ggml_tensor* mu_mel = nullptr;
    ggml_tensor* cond_mel = nullptr;
    ggml_tensor* spks_mel = nullptr;
    ggml_tensor* pos_ids = nullptr;

    // Output tensors
    ggml_tensor* dphi_cond_t = nullptr;
    ggml_tensor* dphi_uncond_t = nullptr;
    ggml_tensor* dphi_final = nullptr;
    ggml_tensor* x_new_t = nullptr;

    // Graph
    ggml_cgraph* gf = nullptr;

    // Schedule
    std::vector<float> t_span;
    float cfg_rate = 0.7f;

    ~OdeTestContext() {
        if (buf) ggml_backend_buffer_free(buf);
        if (backend) ggml_backend_free(backend);
        if (ctx) ggml_free(ctx);
    }
};

static bool build_ode_test_context(
    OdeTestContext& tc,
    const char* model_path,
    const gold_tensor& gold_x,
    const gold_tensor& gold_mu)
{
    gguf_file model(model_path);
    if (!model) return false;

    tc.cfg_rate = model.get_f32("decoder.inference_cfg_rate");
    if (tc.cfg_rate < 0.f) tc.cfg_rate = 0.7f;

    tc.t_span.resize(N_STEPS);
    for (int i = 0; i < N_STEPS; i++)
        tc.t_span[i] = 1.f - std::cos(0.1f * 0.5f * (float)M_PI * (float)i);

    ggml_init_params params = {
        .mem_size = (size_t)4096 * 1024 * 1024,
        .mem_buffer = nullptr,
        .no_alloc = true,
    };
    tc.ctx = ggml_init(params);
    if (!tc.ctx) return false;

    // Input tensors
    tc.t_scalar = make_f32(tc.ctx, 1);
    tc.emb_coeff = make_f32(tc.ctx, HALF_DIM);
    tc.x_mel    = make_f32(tc.ctx, MEL_DIM, SUB_SEQ, BATCH);
    tc.mu_mel   = make_f32(tc.ctx, MEL_DIM, SUB_SEQ, BATCH);
    tc.cond_mel = make_f32(tc.ctx, MEL_DIM, SUB_SEQ, BATCH);
    tc.spks_mel = make_f32(tc.ctx, MEL_DIM, SUB_SEQ, BATCH);
    tc.pos_ids  = ggml_new_tensor_2d(tc.ctx, GGML_TYPE_I32, SUB_SEQ, BATCH);
    ggml_set_input(tc.pos_ids);

    // Load weights
    auto* ie_pw_gguf = model.tensor("decoder.estimator.input_embed.proj.weight");
    auto* ie_pb_gguf = model.tensor("decoder.estimator.input_embed.proj.bias");
    auto* tml0_w_gguf = model.tensor("decoder.estimator.time_embed.time_mlp.0.weight");
    auto* tml0_b_gguf = model.tensor("decoder.estimator.time_embed.time_mlp.0.bias");
    auto* tml2_w_gguf = model.tensor("decoder.estimator.time_embed.time_mlp.2.weight");
    auto* tml2_b_gguf = model.tensor("decoder.estimator.time_embed.time_mlp.2.bias");
    if (!ie_pw_gguf || !ie_pb_gguf || !tml0_w_gguf || !tml0_b_gguf || !tml2_w_gguf || !tml2_b_gguf)
        return false;

    auto* ie_pw = make_f32(tc.ctx, ie_pw_gguf->ne[0], ie_pw_gguf->ne[1]);
    auto* ie_pb = make_f32(tc.ctx, ie_pb_gguf->ne[0]);
    auto* tml0_w = make_f32(tc.ctx, tml0_w_gguf->ne[0], tml0_w_gguf->ne[1]);
    auto* tml0_b = make_f32(tc.ctx, tml0_b_gguf->ne[0]);
    auto* tml2_w = make_f32(tc.ctx, tml2_w_gguf->ne[0], tml2_w_gguf->ne[1]);
    auto* tml2_b = make_f32(tc.ctx, tml2_b_gguf->ne[0]);

    std::vector<BlockWeights> bw(DEPTH), bw_gguf(DEPTH);
    for (int i = 0; i < DEPTH; i++) {
        char pfx[128];
        #define LOAD(field, suffix) do { \
            snprintf(pfx, sizeof(pfx), "decoder.estimator.transformer_blocks.%d.%s", i, suffix); \
            bw_gguf[i].field = model.tensor(pfx); \
            if (!bw_gguf[i].field) return false; \
            bw[i].field = make_f32(tc.ctx, bw_gguf[i].field->ne[0], \
                bw_gguf[i].field->ne[1] > 1 ? bw_gguf[i].field->ne[1] : 1); \
        } while(0)
        LOAD(aln_w, "attn_norm.linear.weight"); LOAD(aln_b, "attn_norm.linear.bias");
        LOAD(qw, "attn.to_q.weight"); LOAD(qb, "attn.to_q.bias");
        LOAD(kw, "attn.to_k.weight"); LOAD(kb, "attn.to_k.bias");
        LOAD(vw, "attn.to_v.weight"); LOAD(vb, "attn.to_v.bias");
        LOAD(ow, "attn.to_out.0.weight"); LOAD(ob, "attn.to_out.0.bias");
        LOAD(fuw, "ff.ff.0.0.weight"); LOAD(fub, "ff.ff.0.0.bias");
        LOAD(fdw, "ff.ff.2.weight"); LOAD(fdb, "ff.ff.2.bias");
        #undef LOAD
    }

    auto* no_w_gguf = model.tensor("decoder.estimator.norm_out.linear.weight");
    auto* no_b_gguf = model.tensor("decoder.estimator.norm_out.linear.bias");
    auto* po_w_gguf = model.tensor("decoder.estimator.proj_out.weight");
    auto* po_b_gguf = model.tensor("decoder.estimator.proj_out.bias");
    if (!no_w_gguf || !no_b_gguf || !po_w_gguf || !po_b_gguf) return false;

    auto* no_w = make_f32(tc.ctx, no_w_gguf->ne[0], no_w_gguf->ne[1]);
    auto* no_b = make_f32(tc.ctx, no_b_gguf->ne[0]);
    auto* po_w = make_f32(tc.ctx, po_w_gguf->ne[0], po_w_gguf->ne[1]);
    auto* po_b = make_f32(tc.ctx, po_b_gguf->ne[0]);

    // --- Build graph ---

    // Timestep embedding
    auto* t_rep = ggml_repeat(tc.ctx, tc.t_scalar, tc.emb_coeff);
    auto* t_mul = ggml_mul(tc.ctx, t_rep, tc.emb_coeff);
    auto* sin_part = ggml_sin(tc.ctx, t_mul);
    auto* cos_part = ggml_cos(tc.ctx, t_mul);
    auto* sinpos = ggml_concat(tc.ctx, sin_part, cos_part, 0);
    auto* time_emb = build_linear(tc.ctx, sinpos, tml0_w, tml0_b);
    time_emb = ggml_silu(tc.ctx, time_emb);
    time_emb = build_linear(tc.ctx, time_emb, tml2_w, tml2_b);

    // InputEmbedding
    auto* ie_input = ggml_concat(tc.ctx, tc.x_mel, tc.cond_mel, 0);
    ie_input = ggml_concat(tc.ctx, ie_input, tc.mu_mel, 0);
    ie_input = ggml_concat(tc.ctx, ie_input, tc.spks_mel, 0);
    auto* ie_output = build_linear(tc.ctx, ie_input, ie_pw, ie_pb);

    // 22 DiT blocks
    auto* cur = ie_output;
    for (int i = 0; i < DEPTH; i++)
        cur = build_dit_block(tc.ctx, cur, time_emb, tc.pos_ids, bw[i], SUB_SEQ, BATCH);

    // AdaLayerNorm_Final + proj_out
    auto* emb_final = ggml_silu(tc.ctx, time_emb);
    emb_final = build_linear(tc.ctx, emb_final, no_w, no_b);
    ggml_tensor* final_ch[2];
    split2(tc.ctx, emb_final, final_ch);
    auto* f_scale = ggml_scale_bias(tc.ctx, ggml_cont(tc.ctx, final_ch[0]), 1.f, 1.f);
    auto* f_shift = ggml_cont(tc.ctx, final_ch[1]);
    cur = ggml_norm(tc.ctx, cur, 1e-6f);
    cur = ggml_mul(tc.ctx, cur, unsqueeze(tc.ctx, f_scale, 1));
    cur = ggml_add(tc.ctx, cur, unsqueeze(tc.ctx, f_shift, 1));
    auto* dit_out = build_linear(tc.ctx, cur, po_w, po_b);

    // Split batch → CFG
    tc.dphi_cond_t = ggml_cont(tc.ctx, ggml_view_3d(tc.ctx, dit_out, MEL_DIM, SUB_SEQ, 1,
        dit_out->nb[1], dit_out->nb[2], 0));
    tc.dphi_uncond_t = ggml_cont(tc.ctx, ggml_view_3d(tc.ctx, dit_out, MEL_DIM, SUB_SEQ, 1,
        dit_out->nb[1], dit_out->nb[2], dit_out->nb[2]));
    ggml_set_output(tc.dphi_cond_t);
    ggml_set_output(tc.dphi_uncond_t);

    tc.dphi_final = ggml_sub(tc.ctx,
        ggml_scale(tc.ctx, tc.dphi_cond_t, 1.f + tc.cfg_rate),
        ggml_scale(tc.ctx, tc.dphi_uncond_t, tc.cfg_rate));
    ggml_set_output(tc.dphi_final);

    // Euler step: x_new = x_old (batch 0) + dt * dphi_final
    // dt is applied via ggml_scale; we patch its op_params per step
    auto* x_old_t = ggml_cont(tc.ctx, ggml_view_3d(tc.ctx, tc.x_mel, MEL_DIM, SUB_SEQ, 1,
        tc.x_mel->nb[1], tc.x_mel->nb[2], 0));
    auto* dt_scaled_dphi = ggml_scale(tc.ctx, tc.dphi_final, 1.0f); // placeholder dt=1.0
    tc.x_new_t = ggml_add(tc.ctx, x_old_t, dt_scaled_dphi);
    ggml_set_output(tc.x_new_t);

    // Build graph
    tc.gf = ggml_new_graph_custom(tc.ctx, 262144, false);
    ggml_build_forward_expand(tc.gf, tc.x_new_t);

    // Allocate backend
    tc.backend = ggml_backend_cpu_init();
    if (!tc.backend) return false;
    tc.buf = ggml_backend_alloc_ctx_tensors(tc.ctx, tc.backend);
    if (!tc.buf) return false;

    // Fill weights
    fill_from_gguf(ie_pw, ie_pw_gguf); fill_from_gguf(ie_pb, ie_pb_gguf);
    fill_from_gguf(tml0_w, tml0_w_gguf); fill_from_gguf(tml0_b, tml0_b_gguf);
    fill_from_gguf(tml2_w, tml2_w_gguf); fill_from_gguf(tml2_b, tml2_b_gguf);
    for (int i = 0; i < DEPTH; i++) {
        fill_from_gguf(bw[i].aln_w, bw_gguf[i].aln_w); fill_from_gguf(bw[i].aln_b, bw_gguf[i].aln_b);
        fill_from_gguf(bw[i].qw, bw_gguf[i].qw); fill_from_gguf(bw[i].qb, bw_gguf[i].qb);
        fill_from_gguf(bw[i].kw, bw_gguf[i].kw); fill_from_gguf(bw[i].kb, bw_gguf[i].kb);
        fill_from_gguf(bw[i].vw, bw_gguf[i].vw); fill_from_gguf(bw[i].vb, bw_gguf[i].vb);
        fill_from_gguf(bw[i].ow, bw_gguf[i].ow); fill_from_gguf(bw[i].ob, bw_gguf[i].ob);
        fill_from_gguf(bw[i].fuw, bw_gguf[i].fuw); fill_from_gguf(bw[i].fub, bw_gguf[i].fub);
        fill_from_gguf(bw[i].fdw, bw_gguf[i].fdw); fill_from_gguf(bw[i].fdb, bw_gguf[i].fdb);
    }
    fill_from_gguf(no_w, no_w_gguf); fill_from_gguf(no_b, no_b_gguf);
    fill_from_gguf(po_w, po_w_gguf); fill_from_gguf(po_b, po_b_gguf);

    // Fill static inputs
    {
        std::vector<float> coeff(HALF_DIM);
        for (int i = 0; i < HALF_DIM; i++)
            coeff[i] = std::exp((float)i * (-std::log(10000.f) / (HALF_DIM - 1))) * 1000.f;
        ggml_backend_tensor_set(tc.emb_coeff, coeff.data(), 0, coeff.size() * sizeof(float));
    }
    {
        size_t batch_bytes = MEL_DIM * SUB_SEQ * sizeof(float);
        // mu: batch 0 = gold, batch 1 = zeros
        ggml_backend_tensor_set(tc.mu_mel, gold_mu.data.data(), 0, batch_bytes);
        std::vector<float> zeros(MEL_DIM * SUB_SEQ, 0.f);
        ggml_backend_tensor_set(tc.mu_mel, zeros.data(), batch_bytes, batch_bytes);
        // cond, spks: all zeros
        std::vector<float> zeros2(MEL_DIM * SUB_SEQ * BATCH, 0.f);
        ggml_backend_tensor_set(tc.cond_mel, zeros2.data(), 0, zeros2.size() * sizeof(float));
        ggml_backend_tensor_set(tc.spks_mel, zeros2.data(), 0, zeros2.size() * sizeof(float));
    }
    {
        std::vector<int32_t> pids(SUB_SEQ * BATCH);
        for (int i = 0; i < SUB_SEQ * BATCH; i++) pids[i] = i % SUB_SEQ;
        ggml_backend_tensor_set(tc.pos_ids, pids.data(), 0, pids.size() * sizeof(int32_t));
    }

    // Set initial x state
    {
        size_t batch_bytes = MEL_DIM * SUB_SEQ * sizeof(float);
        ggml_backend_tensor_set(tc.x_mel, gold_x.data.data(), 0, batch_bytes);
        ggml_backend_tensor_set(tc.x_mel, gold_x.data.data(), batch_bytes, batch_bytes);
    }

    return true;
}

// Find the dt scale node in the graph (the ggml_scale applied to dphi_final)
static ggml_tensor* find_dt_scale_node(ggml_tensor* x_new) {
    // x_new = add(x_old, scale(dphi_final, dt))
    // x_new->src[1] = scale(dphi_final, dt)
    auto* scale_node = x_new->src[1];
    if (scale_node && scale_node->op == GGML_OP_SCALE)
        return scale_node;
    return nullptr;
}

// Run one ODE step: set t, dt, compute graph, extract x_new, copy back to x_mel
static bool run_step(OdeTestContext& tc, float t_val, float dt_val,
                     std::vector<float>& x_result) {
    // Set t
    ggml_backend_tensor_set(tc.t_scalar, &t_val, 0, sizeof(float));

    // Patch dt on the scale node
    auto* dt_node = find_dt_scale_node(tc.x_new_t);
    if (!dt_node) return false;
    reinterpret_cast<float*>(dt_node->op_params)[0] = dt_val;

    // Compute
    auto status = ggml_backend_graph_compute(tc.backend, tc.gf);
    if (status != GGML_STATUS_SUCCESS) return false;

    // Extract x_new
    size_t n = MEL_DIM * SUB_SEQ;
    x_result.resize(n);
    ggml_backend_tensor_get(tc.x_new_t, x_result.data(), 0, n * sizeof(float));

    // Copy x_new back to x_mel for next step (both batches)
    size_t batch_bytes = n * sizeof(float);
    ggml_backend_tensor_set(tc.x_mel, x_result.data(), 0, batch_bytes);
    ggml_backend_tensor_set(tc.x_mel, x_result.data(), batch_bytes, batch_bytes);

    return true;
}


SCENARIO("Given real voice clone data, "
         "when 10-step ODE runs with correct t/dt, "
         "then per-step mel output matches PyTorch gold",
         "[e2e][ode_full][correct]") {

    auto* model_path = std::getenv("COSYVOICE_TEST_MODEL");
    if (!model_path) { SKIP("Set COSYVOICE_TEST_MODEL"); return; }

    // Load initial state
    gold_tensor gold_x, gold_mu;
    if (!load_gold("initial_x", gold_x) || !load_gold("initial_mu", gold_mu)) {
        SKIP("Gold not found. Run: cd tests && uv run python gen_e2e_ode_full_gold.py");
        return;
    }

    // Load per-step gold
    gold_tensor gold_steps[9];  // steps 2-10
    for (int s = 2; s <= 10; s++) {
        char name[64];
        snprintf(name, sizeof(name), "correct_step%02d_x", s);
        if (!load_gold(name, gold_steps[s - 2])) {
            SKIP("Gold not found. Run: cd tests && uv run python gen_e2e_ode_full_gold.py");
            return;
        }
    }

    OdeTestContext tc;
    REQUIRE(build_ode_test_context(tc, model_path, gold_x, gold_mu));

    printf("\n=== 10-step ODE (correct t/dt) ===\n");

    double max_step_diff = 0;
    std::vector<float> x_result;

    for (int step = 2; step <= 10; step++) {
        float t_val, dt_val;
        get_t_and_dt(tc.t_span, step, t_val, dt_val);

        REQUIRE(run_step(tc, t_val, dt_val, x_result));

        float x_mean = tensor_mean(x_result.data(), MEL_DIM * SUB_SEQ);
        float gold_mean = tensor_mean(gold_steps[step - 2].data.data(), MEL_DIM * SUB_SEQ);

        char label[64];
        snprintf(label, sizeof(label), "step%02d (t=%.4f dt=%.4f)", step, t_val, dt_val);
        auto md = compare_tensors(x_result.data(), gold_steps[step - 2].data.data(),
                                  MEL_DIM * SUB_SEQ, label);
        printf("    x_mean=%.6f (gold=%.6f)\n", x_mean, gold_mean);

        max_step_diff = std::max(max_step_diff, md);
    }

    THEN("all steps match PyTorch within tolerance") {
        printf("  max_step_diff across all steps: %.6f\n", max_step_diff);
        REQUIRE(max_step_diff < 10.0);
    }

    THEN("final mel mean is close to PyTorch") {
        float final_mean = tensor_mean(x_result.data(), MEL_DIM * SUB_SEQ);
        float gold_mean = tensor_mean(gold_steps[8].data.data(), MEL_DIM * SUB_SEQ);
        float diff = std::abs(final_mean - gold_mean);
        printf("  final x_mean=%.6f, gold=%.6f, diff=%.6f\n", final_mean, gold_mean, diff);
        REQUIRE(diff < 1.0f);
    }
}


SCENARIO("Given real voice clone data, "
         "when 10-step ODE reproduces production step2 bug, "
         "then per-step mel output matches PyTorch prodmatch gold",
         "[e2e][ode_full][prodmatch]") {

    auto* model_path = std::getenv("COSYVOICE_TEST_MODEL");
    if (!model_path) { SKIP("Set COSYVOICE_TEST_MODEL"); return; }

    gold_tensor gold_x, gold_mu;
    if (!load_gold("initial_x", gold_x) || !load_gold("initial_mu", gold_mu)) {
        SKIP("Gold not found. Run: cd tests && uv run python gen_e2e_ode_full_gold.py");
        return;
    }

    gold_tensor gold_steps[9];
    gold_tensor gold_correct_steps[9];
    for (int s = 2; s <= 10; s++) {
        char name[64];
        snprintf(name, sizeof(name), "prodmatch_step%02d_x", s);
        if (!load_gold(name, gold_steps[s - 2])) {
            SKIP("Gold not found. Run: cd tests && uv run python gen_e2e_ode_full_gold.py");
            return;
        }
        snprintf(name, sizeof(name), "correct_step%02d_x", s);
        load_gold(name, gold_correct_steps[s - 2]);  // optional, for divergence reporting
    }

    OdeTestContext tc;
    REQUIRE(build_ode_test_context(tc, model_path, gold_x, gold_mu));

    printf("\n=== 10-step ODE (prodmatch: step2 uses step1 t/dt) ===\n");

    double max_step_diff = 0;
    std::vector<float> x_result;

    for (int step = 2; step <= 10; step++) {
        float t_val, dt_val;
        if (step == 2) {
            // BUG reproduction: step 2 uses step 1's t/dt
            get_t_and_dt(tc.t_span, 1, t_val, dt_val);
        } else {
            get_t_and_dt(tc.t_span, step, t_val, dt_val);
        }

        REQUIRE(run_step(tc, t_val, dt_val, x_result));

        float x_mean = tensor_mean(x_result.data(), MEL_DIM * SUB_SEQ);
        float gold_mean = tensor_mean(gold_steps[step - 2].data.data(), MEL_DIM * SUB_SEQ);

        char label[64];
        snprintf(label, sizeof(label), "step%02d (t=%.4f dt=%.4f)", step, t_val, dt_val);
        auto md = compare_tensors(x_result.data(), gold_steps[step - 2].data.data(),
                                  MEL_DIM * SUB_SEQ, label);

        // Report divergence from correct pattern
        float correct_mean = tensor_mean(gold_correct_steps[step - 2].data.data(), MEL_DIM * SUB_SEQ);
        printf("    x_mean=%.6f (prodmatch_gold=%.6f, correct_gold=%.6f, delta=%.6f)\n",
               x_mean, gold_mean, correct_mean, gold_mean - correct_mean);

        max_step_diff = std::max(max_step_diff, md);
    }

    THEN("C++ matches PyTorch prodmatch pattern") {
        printf("  max_step_diff across all steps: %.6f\n", max_step_diff);
        REQUIRE(max_step_diff < 10.0);
    }

    THEN("step2 bug impact is quantified") {
        // Compare prodmatch final vs correct final
        float prodmatch_mean = tensor_mean(gold_steps[8].data.data(), MEL_DIM * SUB_SEQ);
        float correct_mean = tensor_mean(gold_correct_steps[8].data.data(), MEL_DIM * SUB_SEQ);
        float divergence = std::abs(prodmatch_mean - correct_mean);
        printf("  step2 bug final impact: prodmatch_mean=%.6f, correct_mean=%.6f, divergence=%.6f\n",
               prodmatch_mean, correct_mean, divergence);
        // Just report, don't fail — this quantifies the bug
        INFO("Step2 bug causes final mean divergence of " << divergence);
    }
}


// --- Step2 t/dt scheduling bug: regression test ---
// cosyvoice-tts.cpp:358 calls build_cgraph_one_step(ctx, ditctx, step=1, ...)
// for the second ODE step, causing it to use step 1's t/dt instead of step 2's.
//
// This test verifies that the bug exists (step2 with wrong t/dt produces
// different output than step2 with correct t/dt). When the bug is fixed
// in cosyvoice-tts.cpp, update this test to assert they are EQUAL instead.

SCENARIO("Given real voice clone data, "
         "when step 2 runs with step 1 t/dt vs correct t/dt, "
         "then outputs diverge (documents cosyvoice-tts.cpp:358 bug)",
         "[e2e][ode_full][step2_bug]") {

    auto* model_path = std::getenv("COSYVOICE_TEST_MODEL");
    if (!model_path) { SKIP("Set COSYVOICE_TEST_MODEL"); return; }

    gold_tensor gold_x, gold_mu;
    if (!load_gold("initial_x", gold_x) || !load_gold("initial_mu", gold_mu)) {
        SKIP("Gold not found. Run: cd tests && uv run python gen_e2e_ode_full_gold.py");
        return;
    }

    // Run step 2 with CORRECT t/dt
    OdeTestContext tc_correct;
    REQUIRE(build_ode_test_context(tc_correct, model_path, gold_x, gold_mu));

    float t_correct, dt_correct;
    get_t_and_dt(tc_correct.t_span, 2, t_correct, dt_correct);

    std::vector<float> x_correct;
    REQUIRE(run_step(tc_correct, t_correct, dt_correct, x_correct));
    float mean_correct = tensor_mean(x_correct.data(), MEL_DIM * SUB_SEQ);

    // Run step 2 with BUGGY t/dt (step=1 values)
    OdeTestContext tc_buggy;
    REQUIRE(build_ode_test_context(tc_buggy, model_path, gold_x, gold_mu));

    float t_buggy, dt_buggy;
    get_t_and_dt(tc_buggy.t_span, 1, t_buggy, dt_buggy);  // BUG: step=1

    std::vector<float> x_buggy;
    REQUIRE(run_step(tc_buggy, t_buggy, dt_buggy, x_buggy));
    float mean_buggy = tensor_mean(x_buggy.data(), MEL_DIM * SUB_SEQ);

    printf("\n=== Step2 scheduling bug verification ===\n");
    printf("  correct: t=%.6f dt=%.6f → x_mean=%.6f\n", t_correct, dt_correct, mean_correct);
    printf("  buggy:   t=%.6f dt=%.6f → x_mean=%.6f\n", t_buggy, dt_buggy, mean_buggy);

    // Element-wise max diff between correct and buggy outputs
    double max_d = 0;
    for (int i = 0; i < MEL_DIM * SUB_SEQ; i++) {
        double d = std::abs((double)x_correct[i] - (double)x_buggy[i]);
        max_d = std::max(max_d, d);
    }
    float mean_divergence = std::abs(mean_correct - mean_buggy);
    printf("  max_diff=%.6f, mean_divergence=%.6f\n", max_d, mean_divergence);

    THEN("step2 uses wrong t and dt values (bug exists)") {
        // The bug: step 2 gets step 1's schedule instead of its own.
        // step 1: t=0.000, dt=0.012;  step 2 (correct): t=0.012, dt=0.037
        INFO("Bug: cosyvoice-tts.cpp:358 passes step=1 to build_cgraph_one_step for step 2");
        REQUIRE(t_buggy != t_correct);
        REQUIRE(dt_buggy != dt_correct);
        // dt is ~3x smaller with the bug, shrinking the Euler step
        REQUIRE(dt_buggy < dt_correct * 0.5f);
    }

    THEN("buggy step2 output diverges from correct step2") {
        // The two outputs must be measurably different.
        // When the bug is FIXED in cosyvoice-tts.cpp, this assertion will
        // start failing — update to REQUIRE(mean_divergence < 0.001f).
        INFO("mean_divergence=" << mean_divergence << " (correct=" << mean_correct
             << ", buggy=" << mean_buggy << ")");
        REQUIRE(mean_divergence > 0.05f);  // expect ~0.15 divergence
    }
}
