// E2E verification: full 22-block DiT forward pass vs PyTorch gold.
//
// Gold data generated by: uv run python gen_e2e_dit_full_gold.py
// Output dir: /tmp/cv_e2e_dit_full_gold/
//
// This test runs all 22 DiTBlocks sequentially with Q8_0 weights on CPU
// and compares against PyTorch F32 output to measure Q8_0 accumulation error.

#include <catch2/catch_test_macros.hpp>

#include <ggml.h>
#include <gguf.h>
#include <ggml-backend.h>
#include <ggml-cpu.h>

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <string>
#include <vector>

static const int D     = 1024;
static const int D_FF  = 2048;
static const int HEADS = 16;
static const int HD    = D / HEADS;
static const int DEPTH = 22;
static const int SEQ   = 10;
static const int HALF_DIM = 128;

static const char* GOLD_DIR = "/tmp/cv_e2e_dit_full_gold";

struct gold_tensor {
    std::vector<int64_t> shape;
    std::vector<float>   data;
    int64_t numel() const { return (int64_t)data.size(); }
};

static bool load_gold(const char* name, gold_tensor& out) {
    std::string path = std::string(GOLD_DIR) + "/" + name + ".bin";
    std::ifstream f(path, std::ios::binary);
    if (!f) return false;
    uint32_t ndim;
    f.read(reinterpret_cast<char*>(&ndim), 4);
    out.shape.resize(ndim);
    for (uint32_t i = 0; i < ndim; i++) {
        int64_t d; f.read(reinterpret_cast<char*>(&d), 8); out.shape[i] = d;
    }
    int64_t n = 1;
    for (auto d : out.shape) n *= d;
    out.data.resize(n);
    f.read(reinterpret_cast<char*>(out.data.data()), n * sizeof(float));
    return f.good();
}

struct gguf_file {
    gguf_context* gguf_ctx = nullptr;
    ggml_context* ggml_ctx = nullptr;
    explicit gguf_file(const char* path) {
        gguf_ctx = gguf_init_from_file(path,
            gguf_init_params{.no_alloc = false, .ctx = &ggml_ctx});
    }
    ~gguf_file() {
        if (gguf_ctx) gguf_free(gguf_ctx);
        if (ggml_ctx) ggml_free(ggml_ctx);
    }
    explicit operator bool() const { return gguf_ctx != nullptr; }
    ggml_tensor* tensor(const char* name) const {
        return ggml_get_tensor(ggml_ctx, name);
    }
};

static ggml_tensor* make_f32(ggml_context* ctx, int64_t n0, int64_t n1=1, int64_t n2=1) {
    auto* t = ggml_new_tensor_3d(ctx, GGML_TYPE_F32, n0, n1, n2);
    ggml_set_input(t);
    return t;
}

static void fill_from_gguf(ggml_tensor* dst, ggml_tensor* src) {
    int64_t n = ggml_nelements(src);
    if (src->type == GGML_TYPE_F32) {
        ggml_backend_tensor_set(dst, src->data, 0, n * sizeof(float));
    } else {
        std::vector<float> buf(n);
        ggml_get_type_traits(src->type)->to_float(src->data, buf.data(), n);
        ggml_backend_tensor_set(dst, buf.data(), 0, n * sizeof(float));
    }
}

static ggml_tensor* build_linear(ggml_context* ctx, ggml_tensor* x, ggml_tensor* w, ggml_tensor* b) {
    auto* y = ggml_mul_mat(ctx, w, x);
    if (b) {
        auto* bv = ggml_view_4d(ctx, b, b->ne[0], 1, 1, 1,
                                 b->nb[0], b->nb[0], b->nb[0], 0);
        y = ggml_add(ctx, y, bv);
    }
    return y;
}

static ggml_tensor* unsqueeze(ggml_context* ctx, ggml_tensor* x, int dim) {
    if (dim == 1)
        return ggml_view_4d(ctx, x, x->ne[0], 1, x->ne[1], x->ne[2],
                            x->nb[1], x->nb[1], x->nb[2], 0);
    return x;
}

static void split6(ggml_context* ctx, ggml_tensor* t, ggml_tensor** out) {
    int64_t chunk = t->ne[0] / 6;
    for (int i = 0; i < 6; i++)
        out[i] = ggml_view_1d(ctx, t, chunk, i * chunk * sizeof(float));
}

static void split2(ggml_context* ctx, ggml_tensor* t, ggml_tensor** out) {
    int64_t chunk = t->ne[0] / 2;
    for (int i = 0; i < 2; i++)
        out[i] = ggml_view_1d(ctx, t, chunk, i * chunk * sizeof(float));
}

struct BlockWeights {
    ggml_tensor *aln_w, *aln_b;
    ggml_tensor *qw, *qb, *kw, *kb, *vw, *vb, *ow, *ob;
    ggml_tensor *fuw, *fub, *fdw, *fdb;
};

// Build one DiTBlock graph, returning the output tensor
static ggml_tensor* build_dit_block(
    ggml_context* ctx,
    ggml_tensor* x,
    ggml_tensor* emb,
    ggml_tensor* pos_ids,
    const BlockWeights& w,
    int batch)
{
    // AdaLayerNormZero
    auto* emb_s = ggml_silu(ctx, emb);
    auto* emb_p = build_linear(ctx, emb_s, w.aln_w, w.aln_b);

    ggml_tensor* ch[6];
    split6(ctx, emb_p, ch);
    auto* shift_msa = ggml_cont(ctx, ch[0]);
    auto* scale_msa = ggml_scale_bias(ctx, ggml_cont(ctx, ch[1]), 1.f, 1.f);
    auto* gate_msa  = ggml_cont(ctx, ch[2]);
    auto* shift_mlp = ggml_cont(ctx, ch[3]);
    auto* scale_mlp = ggml_scale_bias(ctx, ggml_cont(ctx, ch[4]), 1.f, 1.f);
    auto* gate_mlp  = ggml_cont(ctx, ch[5]);

    auto* xn = ggml_norm(ctx, x, 1e-6f);
    xn = ggml_mul(ctx, xn, unsqueeze(ctx, scale_msa, 1));
    xn = ggml_add(ctx, xn, unsqueeze(ctx, shift_msa, 1));

    // Attention
    auto* q = build_linear(ctx, xn, w.qw, w.qb);
    auto* k = build_linear(ctx, xn, w.kw, w.kb);
    auto* v = build_linear(ctx, xn, w.vw, w.vb);

    q = ggml_reshape_3d(ctx, q, HD, HEADS, SEQ * batch);
    k = ggml_reshape_3d(ctx, k, HD, HEADS, SEQ * batch);
    auto* pos_1d = ggml_reshape_1d(ctx, pos_ids, SEQ * batch);

    q = ggml_rope(ctx, q, pos_1d, HD, GGML_ROPE_TYPE_NORMAL);
    k = ggml_rope(ctx, k, pos_1d, HD, GGML_ROPE_TYPE_NORMAL);

    q = ggml_reshape_4d(ctx, q, HD, HEADS, SEQ, batch);
    k = ggml_reshape_4d(ctx, k, HD, HEADS, SEQ, batch);
    v = ggml_reshape_4d(ctx, v, HD, HEADS, SEQ, batch);

    q = ggml_cont(ctx, ggml_permute(ctx, q, 0, 2, 1, 3));
    k = ggml_cont(ctx, ggml_permute(ctx, k, 0, 2, 1, 3));
    v = ggml_permute(ctx, v, 0, 2, 1, 3);

    auto* scores = ggml_scale(ctx, ggml_mul_mat(ctx, k, q), 1.f / sqrtf((float)HD));
    auto* attn_w = ggml_soft_max(ctx, scores);
    auto* vp = ggml_cont(ctx, ggml_permute(ctx, v, 1, 0, 2, 3));
    auto* attn_out = ggml_cont(ctx, ggml_permute(ctx, ggml_mul_mat(ctx, vp, attn_w), 0, 2, 1, 3));
    attn_out = ggml_reshape_3d(ctx, attn_out, D, SEQ, batch);
    attn_out = build_linear(ctx, attn_out, w.ow, w.ob);

    attn_out = ggml_mul(ctx, attn_out, unsqueeze(ctx, gate_msa, 1));
    x = ggml_add(ctx, x, attn_out);

    // FeedForward
    auto* fn = ggml_norm(ctx, x, 1e-6f);
    fn = ggml_mul(ctx, fn, unsqueeze(ctx, scale_mlp, 1));
    fn = ggml_add(ctx, fn, unsqueeze(ctx, shift_mlp, 1));
    auto* ff = ggml_gelu(ctx, build_linear(ctx, fn, w.fuw, w.fub));
    ff = build_linear(ctx, ff, w.fdw, w.fdb);
    ff = ggml_mul(ctx, ff, unsqueeze(ctx, gate_mlp, 1));
    x = ggml_add(ctx, x, ff);

    return x;
}


SCENARIO("Given all 22 DiTBlock weights from GGUF, "
         "when the full DiT forward pass runs on CPU, "
         "then output matches PyTorch gold (Q8_0 accumulation test)",
         "[e2e][dit_full]") {

    auto* model_path = std::getenv("COSYVOICE_TEST_MODEL");
    if (!model_path) { SKIP("Set COSYVOICE_TEST_MODEL"); return; }

    gold_tensor gold_input, gold_emb, gold_output;
    gold_tensor gold_b00, gold_b05, gold_b10, gold_b15, gold_b21;
    if (!load_gold("full_dit_input", gold_input) ||
        !load_gold("full_dit_time_emb", gold_emb) ||
        !load_gold("full_dit_output", gold_output) ||
        !load_gold("full_dit_after_block00", gold_b00) ||
        !load_gold("full_dit_after_block05", gold_b05) ||
        !load_gold("full_dit_after_block10", gold_b10) ||
        !load_gold("full_dit_after_block15", gold_b15) ||
        !load_gold("full_dit_after_block21", gold_b21)) {
        SKIP("Gold files not found. Run: uv run python gen_e2e_dit_full_gold.py");
        return;
    }

    gguf_file model(model_path);
    REQUIRE(model);

    // Allocate a large context for 22 blocks
    ggml_init_params params = {
        .mem_size = (size_t)2048 * 1024 * 1024,
        .mem_buffer = nullptr,
        .no_alloc = true,
    };
    auto* ctx = ggml_init(params);
    REQUIRE(ctx);

    const int batch = 1;

    // Input + time embedding
    auto* x = make_f32(ctx, D, SEQ, batch);
    auto* emb = make_f32(ctx, D);
    auto* pos_ids = ggml_new_tensor_2d(ctx, GGML_TYPE_I32, SEQ, batch);
    ggml_set_input(pos_ids);

    // Load all 22 block weights
    std::vector<BlockWeights> bw(DEPTH);
    std::vector<BlockWeights> bw_gguf(DEPTH);  // GGUF references

    for (int i = 0; i < DEPTH; i++) {
        char pfx[128];
        #define LOAD(field, suffix) do { \
            snprintf(pfx, sizeof(pfx), "decoder.estimator.transformer_blocks.%d.%s", i, suffix); \
            bw_gguf[i].field = model.tensor(pfx); \
            REQUIRE(bw_gguf[i].field != nullptr); \
            bw[i].field = make_f32(ctx, bw_gguf[i].field->ne[0], \
                bw_gguf[i].field->ne[1] > 1 ? bw_gguf[i].field->ne[1] : 1); \
        } while(0)

        LOAD(aln_w, "attn_norm.linear.weight");
        LOAD(aln_b, "attn_norm.linear.bias");
        LOAD(qw, "attn.to_q.weight"); LOAD(qb, "attn.to_q.bias");
        LOAD(kw, "attn.to_k.weight"); LOAD(kb, "attn.to_k.bias");
        LOAD(vw, "attn.to_v.weight"); LOAD(vb, "attn.to_v.bias");
        LOAD(ow, "attn.to_out.0.weight"); LOAD(ob, "attn.to_out.0.bias");
        LOAD(fuw, "ff.ff.0.0.weight"); LOAD(fub, "ff.ff.0.0.bias");
        LOAD(fdw, "ff.ff.2.weight"); LOAD(fdb, "ff.ff.2.bias");
        #undef LOAD
    }

    // norm_out + proj_out
    auto* no_w_gguf = model.tensor("decoder.estimator.norm_out.linear.weight");
    auto* no_b_gguf = model.tensor("decoder.estimator.norm_out.linear.bias");
    auto* po_w_gguf = model.tensor("decoder.estimator.proj_out.weight");
    auto* po_b_gguf = model.tensor("decoder.estimator.proj_out.bias");
    REQUIRE(no_w_gguf); REQUIRE(no_b_gguf);
    REQUIRE(po_w_gguf); REQUIRE(po_b_gguf);

    auto* no_w = make_f32(ctx, no_w_gguf->ne[0], no_w_gguf->ne[1]);
    auto* no_b = make_f32(ctx, no_b_gguf->ne[0]);
    auto* po_w = make_f32(ctx, po_w_gguf->ne[0], po_w_gguf->ne[1]);
    auto* po_b = make_f32(ctx, po_b_gguf->ne[0]);

    // Build full graph: 22 blocks → norm_out → proj_out
    auto* cur = x;
    ggml_tensor* block_outputs[DEPTH];
    for (int i = 0; i < DEPTH; i++) {
        cur = build_dit_block(ctx, cur, emb, pos_ids, bw[i], batch);
        block_outputs[i] = cur;
        ggml_set_output(cur);
    }

    // AdaLayerNorm_Final
    auto* emb_final = ggml_silu(ctx, emb);
    emb_final = build_linear(ctx, emb_final, no_w, no_b);
    ggml_tensor* final_ch[2];
    split2(ctx, emb_final, final_ch);
    auto* f_scale = ggml_scale_bias(ctx, ggml_cont(ctx, final_ch[0]), 1.f, 1.f);
    auto* f_shift = ggml_cont(ctx, final_ch[1]);

    cur = ggml_norm(ctx, cur, 1e-6f);
    cur = ggml_mul(ctx, cur, unsqueeze(ctx, f_scale, 1));
    cur = ggml_add(ctx, cur, unsqueeze(ctx, f_shift, 1));

    // proj_out
    cur = build_linear(ctx, cur, po_w, po_b);
    ggml_set_output(cur);

    auto* gf = ggml_new_graph_custom(ctx, 131072, false);
    ggml_build_forward_expand(gf, cur);

    auto* backend = ggml_backend_cpu_init();
    REQUIRE(backend);
    auto* buf = ggml_backend_alloc_ctx_tensors(ctx, backend);
    REQUIRE(buf);

    // Fill all weights
    for (int i = 0; i < DEPTH; i++) {
        fill_from_gguf(bw[i].aln_w, bw_gguf[i].aln_w);
        fill_from_gguf(bw[i].aln_b, bw_gguf[i].aln_b);
        fill_from_gguf(bw[i].qw, bw_gguf[i].qw);
        fill_from_gguf(bw[i].qb, bw_gguf[i].qb);
        fill_from_gguf(bw[i].kw, bw_gguf[i].kw);
        fill_from_gguf(bw[i].kb, bw_gguf[i].kb);
        fill_from_gguf(bw[i].vw, bw_gguf[i].vw);
        fill_from_gguf(bw[i].vb, bw_gguf[i].vb);
        fill_from_gguf(bw[i].ow, bw_gguf[i].ow);
        fill_from_gguf(bw[i].ob, bw_gguf[i].ob);
        fill_from_gguf(bw[i].fuw, bw_gguf[i].fuw);
        fill_from_gguf(bw[i].fub, bw_gguf[i].fub);
        fill_from_gguf(bw[i].fdw, bw_gguf[i].fdw);
        fill_from_gguf(bw[i].fdb, bw_gguf[i].fdb);
    }
    fill_from_gguf(no_w, no_w_gguf);
    fill_from_gguf(no_b, no_b_gguf);
    fill_from_gguf(po_w, po_w_gguf);
    fill_from_gguf(po_b, po_b_gguf);

    // Fill inputs
    ggml_backend_tensor_set(x, gold_input.data.data(), 0, gold_input.data.size() * sizeof(float));
    ggml_backend_tensor_set(emb, gold_emb.data.data(), 0, gold_emb.data.size() * sizeof(float));
    {
        std::vector<int32_t> pids(SEQ * batch);
        for (int i = 0; i < SEQ * batch; i++) pids[i] = i % SEQ;
        ggml_backend_tensor_set(pos_ids, pids.data(), 0, pids.size() * sizeof(int32_t));
    }

    INFO("Computing full 22-block DiT graph...");
    auto status = ggml_backend_graph_compute(backend, gf);
    REQUIRE(status == GGML_STATUS_SUCCESS);

    // Compare block outputs at checkpoints
    auto compare_block = [&](int idx, const gold_tensor& gold, const char* label) {
        std::vector<float> result(SEQ * D);
        ggml_backend_tensor_get(block_outputs[idx], result.data(), 0, result.size() * sizeof(float));
        double sum = 0, sum_abs = 0, max_d = 0;
        for (int i = 0; i < SEQ * D; i++) {
            float d = result[i] - gold.data[i];
            sum += d; sum_abs += std::abs(d);
            max_d = std::max(max_d, (double)std::abs(d));
        }
        float mean_diff = (float)(sum / (SEQ * D));
        float mad = (float)(sum_abs / (SEQ * D));
        INFO(label << ": max_diff=" << max_d << " mean_diff=" << mean_diff << " mad=" << mad);
        return max_d;
    };

    THEN("block 0 output matches PyTorch") {
        auto md = compare_block(0, gold_b00, "block00");
        REQUIRE(md < 2.0f);
    }
    THEN("block 5 output matches PyTorch") {
        auto md = compare_block(5, gold_b05, "block05");
        INFO("(Q8_0 error compounds through 6 blocks)");
        REQUIRE(md < 50.0f);  // relaxed — measuring accumulation
    }
    THEN("block 10 output matches PyTorch") {
        auto md = compare_block(10, gold_b10, "block10");
        REQUIRE(md < 200.0f);
    }
    THEN("block 15 output matches PyTorch") {
        auto md = compare_block(15, gold_b15, "block15");
        REQUIRE(md < 500.0f);
    }
    THEN("block 21 output matches PyTorch") {
        auto md = compare_block(21, gold_b21, "block21");
        REQUIRE(md < 1000.0f);  // very relaxed — 22 blocks of Q8_0
    }
    THEN("final output matches PyTorch") {
        std::vector<float> result(SEQ * 80);
        ggml_backend_tensor_get(cur, result.data(), 0, result.size() * sizeof(float));
        double sum = 0, sum_abs = 0, max_d = 0;
        for (int i = 0; i < SEQ * 80; i++) {
            float d = result[i] - gold_output.data[i];
            sum += d; sum_abs += std::abs(d);
            max_d = std::max(max_d, (double)std::abs(d));
        }
        float mean_diff = (float)(sum / (SEQ * 80));
        float mad = (float)(sum_abs / (SEQ * 80));
        INFO("final: max_diff=" << max_d << " mean_diff=" << mean_diff << " mad=" << mad);
        REQUIRE(max_d < 100.0f);  // very relaxed
    }

    ggml_backend_buffer_free(buf);
    ggml_backend_free(backend);
    ggml_free(ctx);
}
